"""Seed data for 55 technicians across all deployability states and archetypes.

Each technician has:
  - Personal info, location, approved regions
  - career_stage, deployability_status, archetype
  - Skill assignments (referencing taxonomy slugs) with proficiency & hours
  - Certification assignments (referencing taxonomy slugs) with dates & status
  - Document verification statuses
  - Site badges where applicable

Deployability states covered:
  Ready Now, In Training, Currently Assigned, Missing Cert,
  Missing Docs, Rolling Off Soon, Inactive

Archetypes covered:
  senior_specialist, generalist, apprentice, traveling_tech, local_only
"""

from datetime import date

# ── Slug → Name mappings (from taxonomy.py) ────────────────────────────────

# Slug shortcuts → actual skill names matching skills_and_certs.py taxonomy
# These map compact slugs used in technician definitions to the canonical names
# in the skills taxonomy.
SKILL_SLUG_TO_NAME = {
    "fiber-splicing": "Fiber Splicing",
    "otdr-testing": "OTDR Testing",
    "fiber-termination": "Fiber Termination",
    "osp-construction": "Underground Construction",
    "fiber-route-design": "Fiber Route Design",
    "cat6-termination": "Copper Termination",
    "cable-pathway": "Pathway & Conduit Routing",
    "cable-cert-testing": "Cable Certification Testing",
    "rack-and-stack": "Rack & Cabinet Mounting",
    "power-distribution": "DC Power Systems",
    "hot-cold-aisle": "Hot/Cold Aisle Containment",
    "cross-connect": "High-Density Fiber Patching",
    "das-installation": "Aerial Construction",
    "small-cell": "PON Systems",
    "rf-testing": "Fiber Cable Pulling",
    "aerial-lift": "Bucket Truck Operations",
    "confined-space": "Safety & Compliance",
    "project-coordination": "Site Survey & Documentation",
    "fiber-cable-pulling": "Fiber Cable Pulling",
    "pon-systems": "PON Systems",
}

# Slug shortcuts → actual cert names matching skills_and_certs.py taxonomy
CERT_SLUG_TO_NAME = {
    "foa-cfot": "FOA CFOT",
    "foa-cfos-s": "FOA CFOS/S",
    "foa-cfos-t": "FOA CFOS/T",
    "bicsi-tech": "BICSI Technician",
    "bicsi-rcdd": "BICSI RCDD",
    "osha-10": "OSHA 10",
    "osha-30": "OSHA 30",
    "first-aid-cpr": "First Aid/CPR/AED",
    "comptia-network-plus": "ETA Fiber Optics Installer",
    "eta-foi": "ETA Fiber Optics Installer",
    "nfpa-70e": "Confined Space Entry",
    "corning-certified": "Corning Certified Installer",
}

# ── Helper to keep definitions compact ──────────────────────────────────────

def _skill(slug: str, level: str, hours: float, last_used: str | None = None):
    """Build a skill dict. Uses slug for compactness; resolved to name at seed time."""
    return {
        "skill_slug": slug,
        "skill_name": SKILL_SLUG_TO_NAME[slug],
        "proficiency_level": level,
        "training_hours_accumulated": hours,
        "last_used_date": last_used,
    }

def _cert(slug: str, issue: str, expiry: str | None, status: str = "Active", cred: str | None = None):
    """Build a cert dict. Uses slug for compactness; resolved to name at seed time."""
    return {
        "cert_slug": slug,
        "cert_name": CERT_SLUG_TO_NAME[slug],
        "issue_date": issue,
        "expiry_date": expiry,
        "status": status,
        "credential_number": cred,
    }

def _doc(doc_type: str, status: str = "Verified"):
    return {"doc_type": doc_type, "verification_status": status}

ALL_DOCS_VERIFIED = [
    _doc("background_check"),
    _doc("drivers_license"),
    _doc("w9"),
    _doc("drug_screen"),
    _doc("safety_training_record"),
    _doc("vehicle_insurance"),
]

DOCS_MISSING_BG = [
    _doc("background_check", "Not Submitted"),
    _doc("drivers_license"),
    _doc("w9"),
    _doc("drug_screen"),
    _doc("safety_training_record"),
    _doc("vehicle_insurance"),
]

DOCS_PENDING = [
    _doc("background_check", "Pending Review"),
    _doc("drivers_license"),
    _doc("w9"),
    _doc("drug_screen", "Pending Review"),
    _doc("safety_training_record"),
    _doc("vehicle_insurance"),
]

DOCS_PARTIAL = [
    _doc("background_check"),
    _doc("drivers_license"),
    _doc("w9", "Not Submitted"),
    _doc("drug_screen"),
    _doc("safety_training_record", "Not Submitted"),
    _doc("vehicle_insurance", "Not Submitted"),
]

# ── Technician Definitions ──────────────────────────────────────────────────

TECHNICIANS = [
    # =====================================================================
    # 1-8: SENIOR SPECIALISTS — highly experienced, deep skill sets
    # =====================================================================
    {
        "first_name": "Marcus",
        "last_name": "Thompson",
        "email": "marcus.thompson@deployable.demo",
        "phone": "555-0101",
        "home_base_city": "Atlanta",
        "home_base_state": "GA",
        "approved_regions": ["GA", "SC", "NC", "FL", "AL"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 500,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "senior_specialist",
        "years_experience": 12.0,
        "total_project_count": 38,
        "total_approved_hours": 8400.0,
        "hourly_rate_min": 42.0,
        "hourly_rate_max": 55.0,
        "docs_verified": True,
        "hire_date": "2014-03-15",
        "ops_notes": "Top-tier splicer. Consistently positive partner feedback. Lead candidate for supervisor track.",
        "skills": [
            _skill("fiber-splicing", "Advanced", 3200.0, "2026-03-10"),
            _skill("otdr-testing", "Advanced", 1800.0, "2026-03-10"),
            _skill("fiber-termination", "Advanced", 1600.0, "2026-02-28"),
            _skill("osp-construction", "Advanced", 1200.0, "2025-12-15"),
            _skill("project-coordination", "Intermediate", 180.0, "2026-03-10"),
            _skill("aerial-lift", "Advanced", 600.0, "2026-01-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2015-06-10", None, "Active", "CFOT-2015-4821"),
            _cert("foa-cfos-s", "2016-09-14", None, "Active", "CFOS-S-2016-1123"),
            _cert("osha-30", "2018-01-20", None, "Active"),
            _cert("first-aid-cpr", "2025-04-10", "2027-04-10", "Active"),
            _cert("corning-certified", "2024-08-01", "2026-08-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "AT&T Cleared", "badge_type": "client"},
            {"badge_name": "Google DC Authorized", "badge_type": "site"},
        ],
    },
    {
        "first_name": "Linda",
        "last_name": "Chen",
        "email": "linda.chen@deployable.demo",
        "phone": "555-0102",
        "home_base_city": "San Jose",
        "home_base_state": "CA",
        "approved_regions": ["CA", "NV", "OR", "WA", "AZ"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 600,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "senior_specialist",
        "years_experience": 15.0,
        "total_project_count": 45,
        "total_approved_hours": 11200.0,
        "hourly_rate_min": 48.0,
        "hourly_rate_max": 62.0,
        "docs_verified": True,
        "hire_date": "2011-07-22",
        "ops_notes": "Data center specialist with exceptional rack & stack speed. Mentors new hires.",
        "skills": [
            _skill("rack-and-stack", "Advanced", 4200.0, "2026-03-12"),
            _skill("power-distribution", "Advanced", 2200.0, "2026-03-12"),
            _skill("hot-cold-aisle", "Advanced", 1800.0, "2026-02-20"),
            _skill("cross-connect", "Advanced", 1500.0, "2026-03-01"),
            _skill("fiber-splicing", "Intermediate", 180.0, "2026-01-15"),
            _skill("cable-cert-testing", "Advanced", 800.0, "2026-03-05"),
            _skill("project-coordination", "Advanced", 500.0, "2026-03-12"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2023-05-15", "2026-05-15", "Active", "BICSI-I2-78342"),
            _cert("osha-30", "2019-03-10", None, "Active"),
            _cert("nfpa-70e", "2025-06-01", "2026-06-01", "Active"),
            _cert("first-aid-cpr", "2025-01-15", "2027-01-15", "Active"),
            _cert("comptia-network-plus", "2022-08-20", "2025-08-20", "Expired"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Equinix Authorized", "badge_type": "site"},
            {"badge_name": "Meta DC Cleared", "badge_type": "client"},
            {"badge_name": "100+ Projects", "badge_type": "milestone"},
        ],
    },
    {
        "first_name": "Robert",
        "last_name": "Williams",
        "email": "robert.williams@deployable.demo",
        "phone": "555-0103",
        "home_base_city": "Dallas",
        "home_base_state": "TX",
        "approved_regions": ["TX", "OK", "LA", "AR", "NM"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 450,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "senior_specialist",
        "years_experience": 10.0,
        "total_project_count": 28,
        "total_approved_hours": 6800.0,
        "hourly_rate_min": 40.0,
        "hourly_rate_max": 52.0,
        "docs_verified": True,
        "hire_date": "2016-01-10",
        "available_from": "2026-03-20",
        "ops_notes": "OSP specialist. Strong in aerial and underground. Available immediately.",
        "skills": [
            _skill("osp-construction", "Advanced", 3500.0, "2026-02-28"),
            _skill("fiber-splicing", "Advanced", 1800.0, "2026-02-28"),
            _skill("otdr-testing", "Intermediate", 220.0, "2026-02-15"),
            _skill("aerial-lift", "Advanced", 800.0, "2026-02-20"),
            _skill("confined-space", "Intermediate", 120.0, "2025-11-30"),
            _skill("fiber-route-design", "Intermediate", 200.0, "2026-01-10"),
        ],
        "certifications": [
            _cert("foa-cfot", "2017-04-22", None, "Active", "CFOT-2017-6190"),
            _cert("osha-30", "2020-02-14", None, "Active"),
            _cert("first-aid-cpr", "2024-11-01", "2026-11-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Lumen Cleared", "badge_type": "client"},
        ],
    },
    {
        "first_name": "Patricia",
        "last_name": "Okafor",
        "email": "patricia.okafor@deployable.demo",
        "phone": "555-0104",
        "home_base_city": "Chicago",
        "home_base_state": "IL",
        "approved_regions": ["IL", "IN", "WI", "MI", "OH", "MN"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 400,
        "career_stage": "Deployed",
        "deployability_status": "Rolling Off Soon",
        "archetype": "senior_specialist",
        "years_experience": 9.0,
        "total_project_count": 24,
        "total_approved_hours": 5600.0,
        "hourly_rate_min": 38.0,
        "hourly_rate_max": 50.0,
        "docs_verified": True,
        "hire_date": "2017-06-01",
        "available_from": "2026-04-15",
        "ops_notes": "DAS specialist. Current project ending mid-April. Pre-book for next engagement.",
        "skills": [
            _skill("das-installation", "Advanced", 2400.0, "2026-03-15"),
            _skill("small-cell", "Advanced", 1200.0, "2026-03-10"),
            _skill("rf-testing", "Advanced", 900.0, "2026-03-15"),
            _skill("fiber-splicing", "Intermediate", 150.0, "2025-08-20"),
            _skill("cable-pathway", "Intermediate", 200.0, "2025-06-10"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2022-10-01", "2025-10-01", "Expired", "BICSI-I2-81205"),
            _cert("osha-10", "2018-04-15", None, "Active"),
            _cert("first-aid-cpr", "2025-07-20", "2027-07-20", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Verizon Authorized", "badge_type": "client"},
            {"badge_name": "T-Mobile Site Access", "badge_type": "site"},
        ],
    },
    {
        "first_name": "James",
        "last_name": "Nakamura",
        "email": "james.nakamura@deployable.demo",
        "phone": "555-0105",
        "home_base_city": "Seattle",
        "home_base_state": "WA",
        "approved_regions": ["WA", "OR", "CA", "ID", "MT"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 500,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "senior_specialist",
        "years_experience": 14.0,
        "total_project_count": 42,
        "total_approved_hours": 9800.0,
        "hourly_rate_min": 45.0,
        "hourly_rate_max": 58.0,
        "docs_verified": True,
        "hire_date": "2012-09-01",
        "available_from": "2026-03-19",
        "ops_notes": "OTDR/testing expert. BICSI RCDD candidate. Can lead quality assurance teams.",
        "skills": [
            _skill("otdr-testing", "Advanced", 3800.0, "2026-03-05"),
            _skill("fiber-splicing", "Advanced", 2600.0, "2026-03-05"),
            _skill("fiber-termination", "Advanced", 1400.0, "2026-02-20"),
            _skill("cable-cert-testing", "Advanced", 1200.0, "2026-03-01"),
            _skill("fiber-route-design", "Advanced", 600.0, "2026-01-30"),
            _skill("project-coordination", "Advanced", 450.0, "2026-03-05"),
        ],
        "certifications": [
            _cert("foa-cfot", "2013-02-14", None, "Active", "CFOT-2013-2891"),
            _cert("foa-cfos-s", "2014-06-20", None, "Active"),
            _cert("foa-cfos-t", "2015-08-10", None, "Active"),
            _cert("bicsi-tech", "2023-11-01", "2026-11-01", "Active", "BICSI-I2-92104"),
            _cert("osha-30", "2017-05-20", None, "Active"),
            _cert("first-aid-cpr", "2025-09-01", "2027-09-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Microsoft DC Authorized", "badge_type": "site"},
            {"badge_name": "AWS Cleared", "badge_type": "client"},
            {"badge_name": "10000+ Hours", "badge_type": "milestone"},
        ],
    },
    {
        "first_name": "Angela",
        "last_name": "Rivera",
        "email": "angela.rivera@deployable.demo",
        "phone": "555-0106",
        "home_base_city": "Phoenix",
        "home_base_state": "AZ",
        "approved_regions": ["AZ", "NV", "CA", "NM", "UT", "CO"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 600,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "senior_specialist",
        "years_experience": 11.0,
        "total_project_count": 32,
        "total_approved_hours": 7200.0,
        "hourly_rate_min": 40.0,
        "hourly_rate_max": 54.0,
        "docs_verified": True,
        "hire_date": "2015-04-20",
        "ops_notes": "Power distribution expert. Leads DC buildout crews. Bilingual English/Spanish.",
        "skills": [
            _skill("power-distribution", "Advanced", 3000.0, "2026-03-14"),
            _skill("rack-and-stack", "Advanced", 2200.0, "2026-03-14"),
            _skill("hot-cold-aisle", "Intermediate", 180.0, "2026-02-10"),
            _skill("cross-connect", "Intermediate", 200.0, "2026-01-25"),
            _skill("project-coordination", "Intermediate", 160.0, "2026-03-14"),
            _skill("cable-pathway", "Advanced", 600.0, "2025-10-20"),
        ],
        "certifications": [
            _cert("nfpa-70e", "2025-03-01", "2026-03-01", "Active"),
            _cert("osha-30", "2019-07-15", None, "Active"),
            _cert("bicsi-tech", "2024-01-10", "2027-01-10", "Active", "BICSI-I2-95001"),
            _cert("first-aid-cpr", "2024-12-01", "2026-12-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "CyrusOne Authorized", "badge_type": "site"},
        ],
    },
    {
        "first_name": "Derek",
        "last_name": "Patel",
        "email": "derek.patel@deployable.demo",
        "phone": "555-0107",
        "home_base_city": "Denver",
        "home_base_state": "CO",
        "approved_regions": ["CO", "WY", "UT", "NM", "KS", "NE"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 500,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Missing Cert",
        "archetype": "senior_specialist",
        "years_experience": 8.0,
        "total_project_count": 20,
        "total_approved_hours": 4800.0,
        "hourly_rate_min": 38.0,
        "hourly_rate_max": 48.0,
        "docs_verified": True,
        "hire_date": "2018-02-15",
        "available_from": "2026-03-25",
        "ops_notes": "Strong splicer but CFOT expired during gap. Needs renewal before next deploy.",
        "skills": [
            _skill("fiber-splicing", "Advanced", 2400.0, "2025-12-20"),
            _skill("fiber-termination", "Advanced", 1200.0, "2025-12-20"),
            _skill("otdr-testing", "Intermediate", 250.0, "2025-11-30"),
            _skill("osp-construction", "Intermediate", 180.0, "2025-09-15"),
            _skill("aerial-lift", "Intermediate", 120.0, "2025-10-01"),
        ],
        "certifications": [
            _cert("foa-cfot", "2019-01-10", None, "Expired", "CFOT-2019-7744"),
            _cert("osha-10", "2018-06-01", None, "Active"),
            _cert("first-aid-cpr", "2024-06-15", "2026-06-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Evelyn",
        "last_name": "Washington",
        "email": "evelyn.washington@deployable.demo",
        "phone": "555-0108",
        "home_base_city": "Charlotte",
        "home_base_state": "NC",
        "approved_regions": ["NC", "SC", "VA", "GA", "TN"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 350,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "senior_specialist",
        "years_experience": 13.0,
        "total_project_count": 36,
        "total_approved_hours": 8000.0,
        "hourly_rate_min": 44.0,
        "hourly_rate_max": 56.0,
        "docs_verified": True,
        "hire_date": "2013-08-12",
        "ops_notes": "Cross-connect specialist. Preferred tech for Equinix jobs. Extremely reliable.",
        "skills": [
            _skill("cross-connect", "Advanced", 3200.0, "2026-03-18"),
            _skill("rack-and-stack", "Advanced", 2000.0, "2026-03-18"),
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-01-10"),
            _skill("fiber-termination", "Advanced", 1000.0, "2026-03-10"),
            _skill("cable-cert-testing", "Intermediate", 180.0, "2026-02-28"),
            _skill("hot-cold-aisle", "Intermediate", 120.0, "2025-11-20"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2024-03-15", "2027-03-15", "Active", "BICSI-I2-97210"),
            _cert("foa-cfot", "2014-11-20", None, "Active", "CFOT-2014-3892"),
            _cert("osha-10", "2014-01-10", None, "Active"),
            _cert("first-aid-cpr", "2025-05-01", "2027-05-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Equinix Authorized", "badge_type": "site"},
            {"badge_name": "QTS Cleared", "badge_type": "site"},
        ],
    },

    # =====================================================================
    # 9-20: GENERALISTS — broad skill sets, mid-experience
    # =====================================================================
    {
        "first_name": "Carlos",
        "last_name": "Mendez",
        "email": "carlos.mendez@deployable.demo",
        "phone": "555-0109",
        "home_base_city": "Houston",
        "home_base_state": "TX",
        "approved_regions": ["TX", "LA", "OK", "AR"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 350,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "generalist",
        "years_experience": 5.0,
        "total_project_count": 14,
        "total_approved_hours": 3200.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": True,
        "hire_date": "2021-04-01",
        "available_from": "2026-03-22",
        "ops_notes": "Solid generalist. Can do fiber and copper equally well. Good team player.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 180.0, "2026-02-28"),
            _skill("fiber-termination", "Intermediate", 140.0, "2026-02-15"),
            _skill("cat6-termination", "Intermediate", 160.0, "2026-02-28"),
            _skill("cable-pathway", "Intermediate", 120.0, "2026-01-30"),
            _skill("rack-and-stack", "Intermediate", 110.0, "2026-02-10"),
            _skill("otdr-testing", "Apprentice", 60.0, "2026-01-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2022-03-15", None, "Active", "CFOT-2022-11205"),
            _cert("osha-10", "2021-06-01", None, "Active"),
            _cert("first-aid-cpr", "2025-03-10", "2027-03-10", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Samantha",
        "last_name": "Brooks",
        "email": "samantha.brooks@deployable.demo",
        "phone": "555-0110",
        "home_base_city": "Nashville",
        "home_base_state": "TN",
        "approved_regions": ["TN", "KY", "AL", "GA", "MS"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "generalist",
        "years_experience": 6.0,
        "total_project_count": 16,
        "total_approved_hours": 3800.0,
        "hourly_rate_min": 32.0,
        "hourly_rate_max": 42.0,
        "docs_verified": True,
        "hire_date": "2020-09-15",
        "ops_notes": "Flexible generalist. Has done fiber, copper, and some DC work. Reliable attendance.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 160.0, "2026-03-10"),
            _skill("cat6-termination", "Intermediate", 200.0, "2026-03-10"),
            _skill("cable-pathway", "Intermediate", 180.0, "2026-03-05"),
            _skill("rack-and-stack", "Apprentice", 80.0, "2025-12-20"),
            _skill("cable-cert-testing", "Intermediate", 120.0, "2026-02-28"),
            _skill("fiber-termination", "Intermediate", 110.0, "2026-03-01"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-07-20", None, "Active", "CFOT-2021-9845"),
            _cert("osha-10", "2020-11-01", None, "Active"),
            _cert("first-aid-cpr", "2025-08-15", "2027-08-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Kevin",
        "last_name": "O'Brien",
        "email": "kevin.obrien@deployable.demo",
        "phone": "555-0111",
        "home_base_city": "Boston",
        "home_base_state": "MA",
        "approved_regions": ["MA", "CT", "RI", "NH", "VT", "ME", "NY"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "generalist",
        "years_experience": 7.0,
        "total_project_count": 19,
        "total_approved_hours": 4400.0,
        "hourly_rate_min": 35.0,
        "hourly_rate_max": 45.0,
        "docs_verified": True,
        "hire_date": "2019-03-10",
        "available_from": "2026-03-20",
        "ops_notes": "Northeast generalist. Strong copper and fiber. Good in harsh weather conditions.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-02-20"),
            _skill("cat6-termination", "Advanced", 400.0, "2026-03-01"),
            _skill("cable-pathway", "Advanced", 350.0, "2026-02-25"),
            _skill("osp-construction", "Intermediate", 180.0, "2026-01-15"),
            _skill("cable-cert-testing", "Intermediate", 160.0, "2026-02-15"),
            _skill("confined-space", "Apprentice", 40.0, "2025-10-10"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2023-06-01", "2026-06-01", "Active", "BICSI-I2-88776"),
            _cert("osha-10", "2019-05-15", None, "Active"),
            _cert("first-aid-cpr", "2024-10-01", "2026-10-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Verizon Authorized", "badge_type": "client"},
        ],
    },
    {
        "first_name": "Diana",
        "last_name": "Kowalski",
        "email": "diana.kowalski@deployable.demo",
        "phone": "555-0112",
        "home_base_city": "Philadelphia",
        "home_base_state": "PA",
        "approved_regions": ["PA", "NJ", "DE", "MD", "NY"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 250,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "generalist",
        "years_experience": 4.0,
        "total_project_count": 10,
        "total_approved_hours": 2400.0,
        "hourly_rate_min": 28.0,
        "hourly_rate_max": 38.0,
        "docs_verified": True,
        "hire_date": "2022-02-01",
        "ops_notes": "Growing generalist. Good mix of DC and cabling skills. Partner feedback positive.",
        "skills": [
            _skill("rack-and-stack", "Intermediate", 180.0, "2026-03-15"),
            _skill("cross-connect", "Intermediate", 120.0, "2026-03-15"),
            _skill("cat6-termination", "Intermediate", 150.0, "2026-02-28"),
            _skill("cable-pathway", "Intermediate", 130.0, "2026-02-20"),
            _skill("fiber-termination", "Apprentice", 80.0, "2026-01-10"),
        ],
        "certifications": [
            _cert("osha-10", "2022-04-15", None, "Active"),
            _cert("first-aid-cpr", "2025-02-01", "2027-02-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Antonio",
        "last_name": "Garcia",
        "email": "antonio.garcia@deployable.demo",
        "phone": "555-0113",
        "home_base_city": "Miami",
        "home_base_state": "FL",
        "approved_regions": ["FL", "GA", "SC", "AL"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 400,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "generalist",
        "years_experience": 6.5,
        "total_project_count": 18,
        "total_approved_hours": 3600.0,
        "hourly_rate_min": 32.0,
        "hourly_rate_max": 42.0,
        "docs_verified": True,
        "hire_date": "2019-10-15",
        "available_from": "2026-03-21",
        "ops_notes": "Bilingual. Strong in both fiber and DAS. Good for multi-trade projects.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-02-15"),
            _skill("das-installation", "Intermediate", 150.0, "2026-01-30"),
            _skill("small-cell", "Apprentice", 60.0, "2025-11-20"),
            _skill("cat6-termination", "Intermediate", 180.0, "2026-02-10"),
            _skill("cable-pathway", "Intermediate", 140.0, "2026-01-25"),
            _skill("aerial-lift", "Intermediate", 80.0, "2025-12-15"),
        ],
        "certifications": [
            _cert("foa-cfot", "2020-08-10", None, "Active", "CFOT-2020-13412"),
            _cert("osha-10", "2020-01-15", None, "Active"),
            _cert("first-aid-cpr", "2025-06-01", "2027-06-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Rachel",
        "last_name": "Kim",
        "email": "rachel.kim@deployable.demo",
        "phone": "555-0114",
        "home_base_city": "Portland",
        "home_base_state": "OR",
        "approved_regions": ["OR", "WA", "CA", "ID"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Deployed",
        "deployability_status": "Rolling Off Soon",
        "archetype": "generalist",
        "years_experience": 5.5,
        "total_project_count": 15,
        "total_approved_hours": 3400.0,
        "hourly_rate_min": 34.0,
        "hourly_rate_max": 44.0,
        "docs_verified": True,
        "hire_date": "2020-11-01",
        "available_from": "2026-04-01",
        "ops_notes": "Versatile. Current project wrapping up end of March. Strong DC and fiber skills.",
        "skills": [
            _skill("rack-and-stack", "Intermediate", 200.0, "2026-03-12"),
            _skill("fiber-splicing", "Intermediate", 160.0, "2026-03-10"),
            _skill("fiber-termination", "Intermediate", 140.0, "2026-03-08"),
            _skill("hot-cold-aisle", "Apprentice", 60.0, "2026-02-20"),
            _skill("cable-cert-testing", "Intermediate", 110.0, "2026-03-05"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-04-10", None, "Active", "CFOT-2021-10102"),
            _cert("osha-10", "2021-01-20", None, "Active"),
            _cert("first-aid-cpr", "2025-09-15", "2027-09-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Brandon",
        "last_name": "Hughes",
        "email": "brandon.hughes@deployable.demo",
        "phone": "555-0115",
        "home_base_city": "Minneapolis",
        "home_base_state": "MN",
        "approved_regions": ["MN", "WI", "IA", "ND", "SD"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 350,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Missing Docs",
        "archetype": "generalist",
        "years_experience": 4.5,
        "total_project_count": 12,
        "total_approved_hours": 2800.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": False,
        "hire_date": "2021-10-01",
        "available_from": "2026-03-25",
        "ops_notes": "Good generalist. Drug screen and W9 pending — follow up before next placement.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 140.0, "2026-01-30"),
            _skill("cat6-termination", "Intermediate", 160.0, "2026-02-15"),
            _skill("cable-pathway", "Intermediate", 120.0, "2026-01-20"),
            _skill("rack-and-stack", "Apprentice", 70.0, "2025-11-30"),
            _skill("otdr-testing", "Apprentice", 50.0, "2025-12-10"),
        ],
        "certifications": [
            _cert("foa-cfot", "2022-06-15", None, "Active", "CFOT-2022-12340"),
            _cert("osha-10", "2021-12-01", None, "Active"),
        ],
        "documents": DOCS_PARTIAL,
        "site_badges": [],
    },
    {
        "first_name": "Jessica",
        "last_name": "Turner",
        "email": "jessica.turner@deployable.demo",
        "phone": "555-0116",
        "home_base_city": "Raleigh",
        "home_base_state": "NC",
        "approved_regions": ["NC", "VA", "SC", "GA"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "generalist",
        "years_experience": 5.0,
        "total_project_count": 13,
        "total_approved_hours": 3000.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": True,
        "hire_date": "2021-05-01",
        "ops_notes": "Steady performer. Good mix of fiber and cabling. No complaints from partners.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 180.0, "2026-03-15"),
            _skill("fiber-termination", "Intermediate", 150.0, "2026-03-10"),
            _skill("cat6-termination", "Intermediate", 140.0, "2026-02-28"),
            _skill("cable-pathway", "Intermediate", 110.0, "2026-02-15"),
            _skill("cable-cert-testing", "Apprentice", 60.0, "2026-01-30"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-11-01", None, "Active", "CFOT-2021-10890"),
            _cert("osha-10", "2021-07-15", None, "Active"),
            _cert("first-aid-cpr", "2025-04-20", "2027-04-20", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Marcus",
        "last_name": "Jefferson",
        "email": "marcus.jefferson@deployable.demo",
        "phone": "555-0117",
        "home_base_city": "Columbus",
        "home_base_state": "OH",
        "approved_regions": ["OH", "PA", "WV", "IN", "KY"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "generalist",
        "years_experience": 3.5,
        "total_project_count": 9,
        "total_approved_hours": 2200.0,
        "hourly_rate_min": 28.0,
        "hourly_rate_max": 36.0,
        "docs_verified": True,
        "hire_date": "2022-09-01",
        "available_from": "2026-03-20",
        "ops_notes": "Solid generalist progressing well. Ready for intermediate-level solo assignments.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 120.0, "2026-02-28"),
            _skill("cat6-termination", "Intermediate", 140.0, "2026-03-01"),
            _skill("cable-pathway", "Intermediate", 100.0, "2026-02-15"),
            _skill("rack-and-stack", "Apprentice", 60.0, "2026-01-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2023-02-10", None, "Active", "CFOT-2023-14102"),
            _cert("osha-10", "2022-11-15", None, "Active"),
            _cert("first-aid-cpr", "2025-07-01", "2027-07-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Lauren",
        "last_name": "Mitchell",
        "email": "lauren.mitchell@deployable.demo",
        "phone": "555-0118",
        "home_base_city": "San Antonio",
        "home_base_state": "TX",
        "approved_regions": ["TX", "OK", "NM"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 250,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "generalist",
        "years_experience": 4.0,
        "total_project_count": 11,
        "total_approved_hours": 2600.0,
        "hourly_rate_min": 29.0,
        "hourly_rate_max": 38.0,
        "docs_verified": True,
        "hire_date": "2022-03-15",
        "ops_notes": "Good in hot environments. Reliable. Gaining DC experience on current assignment.",
        "skills": [
            _skill("rack-and-stack", "Intermediate", 140.0, "2026-03-15"),
            _skill("power-distribution", "Apprentice", 80.0, "2026-03-10"),
            _skill("fiber-termination", "Intermediate", 110.0, "2026-02-20"),
            _skill("cat6-termination", "Intermediate", 130.0, "2026-02-28"),
            _skill("cable-pathway", "Intermediate", 100.0, "2026-02-10"),
        ],
        "certifications": [
            _cert("osha-10", "2022-05-20", None, "Active"),
            _cert("first-aid-cpr", "2025-01-10", "2027-01-10", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Tyler",
        "last_name": "Robinson",
        "email": "tyler.robinson@deployable.demo",
        "phone": "555-0119",
        "home_base_city": "Indianapolis",
        "home_base_state": "IN",
        "approved_regions": ["IN", "OH", "IL", "KY", "MI"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "generalist",
        "years_experience": 5.5,
        "total_project_count": 15,
        "total_approved_hours": 3400.0,
        "hourly_rate_min": 33.0,
        "hourly_rate_max": 43.0,
        "docs_verified": True,
        "hire_date": "2020-08-01",
        "available_from": "2026-03-22",
        "ops_notes": "Strong generalist. Good with both indoor and outdoor work. Can handle cold weather.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-02-20"),
            _skill("osp-construction", "Intermediate", 160.0, "2026-01-30"),
            _skill("cat6-termination", "Intermediate", 180.0, "2026-02-25"),
            _skill("cable-pathway", "Intermediate", 140.0, "2026-02-10"),
            _skill("aerial-lift", "Apprentice", 50.0, "2025-11-15"),
            _skill("cable-cert-testing", "Apprentice", 70.0, "2026-01-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-02-15", None, "Active", "CFOT-2021-9234"),
            _cert("osha-10", "2020-10-01", None, "Active"),
            _cert("first-aid-cpr", "2025-05-15", "2027-05-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Megan",
        "last_name": "Clark",
        "email": "megan.clark@deployable.demo",
        "phone": "555-0120",
        "home_base_city": "Tampa",
        "home_base_state": "FL",
        "approved_regions": ["FL", "GA", "AL"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 250,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Missing Cert",
        "archetype": "generalist",
        "years_experience": 3.0,
        "total_project_count": 8,
        "total_approved_hours": 1800.0,
        "hourly_rate_min": 26.0,
        "hourly_rate_max": 34.0,
        "docs_verified": True,
        "hire_date": "2023-01-15",
        "available_from": "2026-04-01",
        "ops_notes": "Good potential but First Aid/CPR expired. Scheduled for renewal next week.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 110.0, "2026-01-20"),
            _skill("fiber-termination", "Intermediate", 100.0, "2026-01-15"),
            _skill("cat6-termination", "Apprentice", 80.0, "2025-12-20"),
            _skill("cable-pathway", "Apprentice", 60.0, "2025-12-10"),
        ],
        "certifications": [
            _cert("foa-cfot", "2023-06-10", None, "Active", "CFOT-2023-15678"),
            _cert("osha-10", "2023-03-01", None, "Active"),
            _cert("first-aid-cpr", "2024-02-15", "2026-02-15", "Expired"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },

    # =====================================================================
    # 21-32: APPRENTICES — new to the field, in training
    # =====================================================================
    {
        "first_name": "Jordan",
        "last_name": "Davis",
        "email": "jordan.davis@deployable.demo",
        "phone": "555-0121",
        "home_base_city": "Atlanta",
        "home_base_state": "GA",
        "approved_regions": ["GA", "SC", "NC"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 200,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.5,
        "total_project_count": 1,
        "total_approved_hours": 240.0,
        "hourly_rate_min": 18.0,
        "hourly_rate_max": 22.0,
        "docs_verified": True,
        "hire_date": "2025-09-15",
        "ops_notes": "Eager learner. Shadowing Marcus Thompson. On track for CFOT in 2 months.",
        "skills": [
            _skill("fiber-splicing", "Apprentice", 80.0, "2026-03-15"),
            _skill("fiber-termination", "Apprentice", 60.0, "2026-03-10"),
            _skill("cable-pathway", "Apprentice", 40.0, "2026-02-28"),
            _skill("cat6-termination", "Apprentice", 30.0, "2026-02-20"),
        ],
        "certifications": [
            _cert("osha-10", "2025-10-01", None, "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Aisha",
        "last_name": "Hassan",
        "email": "aisha.hassan@deployable.demo",
        "phone": "555-0122",
        "home_base_city": "Dallas",
        "home_base_state": "TX",
        "approved_regions": ["TX", "OK"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 200,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.3,
        "total_project_count": 0,
        "total_approved_hours": 120.0,
        "hourly_rate_min": 17.0,
        "hourly_rate_max": 21.0,
        "docs_verified": True,
        "hire_date": "2025-12-01",
        "ops_notes": "Career changer from IT support. Picking up fiber quickly. Has CompTIA background.",
        "skills": [
            _skill("fiber-splicing", "Apprentice", 50.0, "2026-03-12"),
            _skill("fiber-termination", "Apprentice", 30.0, "2026-03-05"),
            _skill("cat6-termination", "Apprentice", 25.0, "2026-02-28"),
            _skill("cable-cert-testing", "Apprentice", 15.0, "2026-02-20"),
        ],
        "certifications": [
            _cert("osha-10", "2026-01-10", None, "Active"),
            _cert("comptia-network-plus", "2023-04-15", "2026-04-15", "Active", "NP-2023-78901"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Ethan",
        "last_name": "Nguyen",
        "email": "ethan.nguyen@deployable.demo",
        "phone": "555-0123",
        "home_base_city": "San Jose",
        "home_base_state": "CA",
        "approved_regions": ["CA"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 50,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.2,
        "total_project_count": 0,
        "total_approved_hours": 80.0,
        "hourly_rate_min": 18.0,
        "hourly_rate_max": 22.0,
        "docs_verified": True,
        "hire_date": "2026-01-10",
        "ops_notes": "New hire. Data center track. Mentoring under Linda Chen. Local only for now.",
        "skills": [
            _skill("rack-and-stack", "Apprentice", 40.0, "2026-03-15"),
            _skill("cable-pathway", "Apprentice", 20.0, "2026-03-10"),
            _skill("cat6-termination", "Apprentice", 15.0, "2026-03-05"),
        ],
        "certifications": [
            _cert("osha-10", "2026-02-01", None, "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Brittany",
        "last_name": "Foster",
        "email": "brittany.foster@deployable.demo",
        "phone": "555-0124",
        "home_base_city": "Chicago",
        "home_base_state": "IL",
        "approved_regions": ["IL", "IN", "WI"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 150,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.8,
        "total_project_count": 2,
        "total_approved_hours": 380.0,
        "hourly_rate_min": 19.0,
        "hourly_rate_max": 24.0,
        "docs_verified": True,
        "hire_date": "2025-07-01",
        "ops_notes": "Strong hands-on aptitude. Approaching intermediate threshold on fiber splicing.",
        "skills": [
            _skill("fiber-splicing", "Apprentice", 90.0, "2026-03-14"),
            _skill("fiber-termination", "Apprentice", 75.0, "2026-03-10"),
            _skill("otdr-testing", "Apprentice", 40.0, "2026-02-28"),
            _skill("cat6-termination", "Apprentice", 50.0, "2026-02-20"),
            _skill("cable-pathway", "Apprentice", 35.0, "2026-02-15"),
        ],
        "certifications": [
            _cert("osha-10", "2025-08-15", None, "Active"),
            _cert("first-aid-cpr", "2025-09-01", "2027-09-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Darius",
        "last_name": "Brown",
        "email": "darius.brown@deployable.demo",
        "phone": "555-0125",
        "home_base_city": "Houston",
        "home_base_state": "TX",
        "approved_regions": ["TX"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 100,
        "career_stage": "Screened",
        "deployability_status": "Missing Docs",
        "archetype": "apprentice",
        "years_experience": 0.0,
        "total_project_count": 0,
        "total_approved_hours": 0.0,
        "hourly_rate_min": 16.0,
        "hourly_rate_max": 20.0,
        "docs_verified": False,
        "hire_date": "2026-03-01",
        "ops_notes": "Just screened. Background check in progress. Start training once docs clear.",
        "skills": [],
        "certifications": [],
        "documents": DOCS_MISSING_BG,
        "site_badges": [],
    },
    {
        "first_name": "Sophia",
        "last_name": "Martinez",
        "email": "sophia.martinez@deployable.demo",
        "phone": "555-0126",
        "home_base_city": "Phoenix",
        "home_base_state": "AZ",
        "approved_regions": ["AZ", "NM"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 200,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.4,
        "total_project_count": 1,
        "total_approved_hours": 160.0,
        "hourly_rate_min": 18.0,
        "hourly_rate_max": 22.0,
        "docs_verified": True,
        "hire_date": "2025-11-01",
        "ops_notes": "DAS/wireless track. Learning under Patricia Okafor. Good mechanical skills.",
        "skills": [
            _skill("das-installation", "Apprentice", 60.0, "2026-03-10"),
            _skill("small-cell", "Apprentice", 30.0, "2026-02-28"),
            _skill("cable-pathway", "Apprentice", 35.0, "2026-02-20"),
            _skill("cat6-termination", "Apprentice", 20.0, "2026-02-10"),
        ],
        "certifications": [
            _cert("osha-10", "2025-12-15", None, "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Noah",
        "last_name": "Wilson",
        "email": "noah.wilson@deployable.demo",
        "phone": "555-0127",
        "home_base_city": "Denver",
        "home_base_state": "CO",
        "approved_regions": ["CO", "WY", "UT"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 250,
        "career_stage": "Training Completed",
        "deployability_status": "Ready Now",
        "archetype": "apprentice",
        "years_experience": 1.0,
        "total_project_count": 3,
        "total_approved_hours": 480.0,
        "hourly_rate_min": 20.0,
        "hourly_rate_max": 26.0,
        "docs_verified": True,
        "hire_date": "2025-03-15",
        "available_from": "2026-03-22",
        "ops_notes": "Training completed. Passed CFOT. Ready for first independent assignment.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 110.0, "2026-03-01"),
            _skill("fiber-termination", "Apprentice", 80.0, "2026-02-28"),
            _skill("otdr-testing", "Apprentice", 50.0, "2026-02-20"),
            _skill("cat6-termination", "Apprentice", 60.0, "2026-02-15"),
            _skill("cable-pathway", "Apprentice", 45.0, "2026-02-10"),
        ],
        "certifications": [
            _cert("foa-cfot", "2026-02-15", None, "Active", "CFOT-2026-17890"),
            _cert("osha-10", "2025-05-01", None, "Active"),
            _cert("first-aid-cpr", "2025-06-15", "2027-06-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Olivia",
        "last_name": "Anderson",
        "email": "olivia.anderson@deployable.demo",
        "phone": "555-0128",
        "home_base_city": "Seattle",
        "home_base_state": "WA",
        "approved_regions": ["WA", "OR"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 200,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.6,
        "total_project_count": 1,
        "total_approved_hours": 280.0,
        "hourly_rate_min": 19.0,
        "hourly_rate_max": 24.0,
        "docs_verified": True,
        "hire_date": "2025-09-01",
        "ops_notes": "Data center track. Showing strong aptitude for rack & stack. Studying for CFOT.",
        "skills": [
            _skill("rack-and-stack", "Apprentice", 90.0, "2026-03-12"),
            _skill("cross-connect", "Apprentice", 40.0, "2026-03-05"),
            _skill("cable-pathway", "Apprentice", 55.0, "2026-02-28"),
            _skill("cat6-termination", "Apprentice", 45.0, "2026-02-20"),
            _skill("fiber-termination", "Apprentice", 30.0, "2026-02-10"),
        ],
        "certifications": [
            _cert("osha-10", "2025-10-15", None, "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Jaylen",
        "last_name": "Cooper",
        "email": "jaylen.cooper@deployable.demo",
        "phone": "555-0129",
        "home_base_city": "Charlotte",
        "home_base_state": "NC",
        "approved_regions": ["NC", "SC", "VA"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 200,
        "career_stage": "Sourced",
        "deployability_status": "Missing Docs",
        "archetype": "apprentice",
        "years_experience": 0.0,
        "total_project_count": 0,
        "total_approved_hours": 0.0,
        "hourly_rate_min": 16.0,
        "hourly_rate_max": 20.0,
        "docs_verified": False,
        "hire_date": "2026-03-10",
        "ops_notes": "Sourced from trade school referral. Awaiting initial documentation.",
        "skills": [],
        "certifications": [],
        "documents": DOCS_PENDING,
        "site_badges": [],
    },
    {
        "first_name": "Emma",
        "last_name": "Reyes",
        "email": "emma.reyes@deployable.demo",
        "phone": "555-0130",
        "home_base_city": "Los Angeles",
        "home_base_state": "CA",
        "approved_regions": ["CA", "NV", "AZ"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 250,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.7,
        "total_project_count": 2,
        "total_approved_hours": 320.0,
        "hourly_rate_min": 19.0,
        "hourly_rate_max": 24.0,
        "docs_verified": True,
        "hire_date": "2025-08-15",
        "ops_notes": "Fiber track. Good test scores. Approaching CFOT exam readiness.",
        "skills": [
            _skill("fiber-splicing", "Apprentice", 95.0, "2026-03-15"),
            _skill("fiber-termination", "Apprentice", 70.0, "2026-03-10"),
            _skill("otdr-testing", "Apprentice", 35.0, "2026-02-28"),
            _skill("cable-pathway", "Apprentice", 40.0, "2026-02-20"),
        ],
        "certifications": [
            _cert("osha-10", "2025-09-15", None, "Active"),
            _cert("first-aid-cpr", "2025-10-01", "2027-10-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Liam",
        "last_name": "Schneider",
        "email": "liam.schneider@deployable.demo",
        "phone": "555-0131",
        "home_base_city": "Boston",
        "home_base_state": "MA",
        "approved_regions": ["MA", "CT", "RI", "NH"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 200,
        "career_stage": "In Training",
        "deployability_status": "In Training",
        "archetype": "apprentice",
        "years_experience": 0.4,
        "total_project_count": 1,
        "total_approved_hours": 200.0,
        "hourly_rate_min": 19.0,
        "hourly_rate_max": 23.0,
        "docs_verified": True,
        "hire_date": "2025-11-15",
        "ops_notes": "Former electrician. Quick learner on fiber. IBEW background gives safety edge.",
        "skills": [
            _skill("fiber-splicing", "Apprentice", 70.0, "2026-03-12"),
            _skill("fiber-termination", "Apprentice", 45.0, "2026-03-05"),
            _skill("cable-pathway", "Intermediate", 110.0, "2026-02-28"),
            _skill("confined-space", "Apprentice", 20.0, "2026-02-15"),
        ],
        "certifications": [
            _cert("osha-30", "2021-03-10", None, "Active"),
            _cert("first-aid-cpr", "2025-12-01", "2027-12-01", "Active"),
            _cert("nfpa-70e", "2024-01-15", "2025-01-15", "Expired"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },

    # =====================================================================
    # 33-42: TRAVELING TECHS — wide regional coverage, road warriors
    # =====================================================================
    {
        "first_name": "Shane",
        "last_name": "McAllister",
        "email": "shane.mcallister@deployable.demo",
        "phone": "555-0132",
        "home_base_city": "Nashville",
        "home_base_state": "TN",
        "approved_regions": ["TN", "KY", "AL", "GA", "SC", "NC", "VA", "WV", "OH", "IN", "IL", "MS", "AR", "MO"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 1000,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "traveling_tech",
        "years_experience": 7.0,
        "total_project_count": 22,
        "total_approved_hours": 5200.0,
        "hourly_rate_min": 38.0,
        "hourly_rate_max": 48.0,
        "docs_verified": True,
        "hire_date": "2019-05-01",
        "ops_notes": "True road warrior. Will go anywhere in the Southeast/Midwest. Top per diem earner.",
        "skills": [
            _skill("fiber-splicing", "Advanced", 2200.0, "2026-03-18"),
            _skill("osp-construction", "Advanced", 1500.0, "2026-03-15"),
            _skill("otdr-testing", "Intermediate", 220.0, "2026-03-10"),
            _skill("aerial-lift", "Advanced", 500.0, "2026-03-05"),
            _skill("confined-space", "Intermediate", 80.0, "2026-01-20"),
            _skill("fiber-termination", "Intermediate", 200.0, "2026-02-28"),
        ],
        "certifications": [
            _cert("foa-cfot", "2020-01-15", None, "Active", "CFOT-2020-12001"),
            _cert("foa-cfos-s", "2021-04-10", None, "Active"),
            _cert("osha-30", "2020-06-01", None, "Active"),
            _cert("first-aid-cpr", "2025-03-15", "2027-03-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "AT&T Cleared", "badge_type": "client"},
            {"badge_name": "Lumen Cleared", "badge_type": "client"},
            {"badge_name": "20+ States Worked", "badge_type": "milestone"},
        ],
    },
    {
        "first_name": "Destiny",
        "last_name": "Jackson",
        "email": "destiny.jackson@deployable.demo",
        "phone": "555-0133",
        "home_base_city": "Kansas City",
        "home_base_state": "MO",
        "approved_regions": ["MO", "KS", "OK", "TX", "AR", "NE", "IA", "IL", "IN", "CO"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 800,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "traveling_tech",
        "years_experience": 6.0,
        "total_project_count": 18,
        "total_approved_hours": 4200.0,
        "hourly_rate_min": 34.0,
        "hourly_rate_max": 44.0,
        "docs_verified": True,
        "hire_date": "2020-03-15",
        "available_from": "2026-03-20",
        "ops_notes": "Central US traveler. Prefers 3-6 month engagements. Strong fiber and copper.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 250.0, "2026-02-28"),
            _skill("cat6-termination", "Advanced", 500.0, "2026-03-01"),
            _skill("cable-pathway", "Advanced", 400.0, "2026-02-25"),
            _skill("osp-construction", "Intermediate", 200.0, "2026-01-15"),
            _skill("cable-cert-testing", "Intermediate", 180.0, "2026-02-20"),
            _skill("rack-and-stack", "Intermediate", 120.0, "2025-12-10"),
        ],
        "certifications": [
            _cert("foa-cfot", "2020-09-20", None, "Active", "CFOT-2020-13001"),
            _cert("bicsi-tech", "2022-11-15", "2025-11-15", "Expired", "BICSI-I2-84321"),
            _cert("osha-10", "2020-05-01", None, "Active"),
            _cert("first-aid-cpr", "2025-08-01", "2027-08-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Windstream Cleared", "badge_type": "client"},
        ],
    },
    {
        "first_name": "Victor",
        "last_name": "Petrov",
        "email": "victor.petrov@deployable.demo",
        "phone": "555-0134",
        "home_base_city": "Columbus",
        "home_base_state": "OH",
        "approved_regions": ["OH", "PA", "NY", "NJ", "CT", "MA", "MD", "VA", "WV", "MI", "IN"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 900,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "traveling_tech",
        "years_experience": 8.0,
        "total_project_count": 25,
        "total_approved_hours": 5800.0,
        "hourly_rate_min": 36.0,
        "hourly_rate_max": 46.0,
        "docs_verified": True,
        "hire_date": "2018-06-01",
        "ops_notes": "Northeast corridor specialist. Handles large DC buildouts. Drives own vehicle.",
        "skills": [
            _skill("rack-and-stack", "Advanced", 2400.0, "2026-03-15"),
            _skill("cross-connect", "Advanced", 1200.0, "2026-03-12"),
            _skill("power-distribution", "Intermediate", 250.0, "2026-03-10"),
            _skill("hot-cold-aisle", "Intermediate", 200.0, "2026-02-28"),
            _skill("fiber-splicing", "Intermediate", 180.0, "2026-02-15"),
            _skill("cable-cert-testing", "Intermediate", 160.0, "2026-03-01"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2024-06-01", "2027-06-01", "Active", "BICSI-I2-96102"),
            _cert("osha-30", "2019-09-15", None, "Active"),
            _cert("nfpa-70e", "2025-08-01", "2026-08-01", "Active"),
            _cert("first-aid-cpr", "2025-02-15", "2027-02-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Digital Realty Authorized", "badge_type": "site"},
            {"badge_name": "CoreSite Cleared", "badge_type": "site"},
        ],
    },
    {
        "first_name": "Tamika",
        "last_name": "Rhodes",
        "email": "tamika.rhodes@deployable.demo",
        "phone": "555-0135",
        "home_base_city": "Memphis",
        "home_base_state": "TN",
        "approved_regions": ["TN", "MS", "AL", "AR", "LA", "TX", "GA", "MO"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 700,
        "career_stage": "Deployed",
        "deployability_status": "Rolling Off Soon",
        "archetype": "traveling_tech",
        "years_experience": 5.0,
        "total_project_count": 14,
        "total_approved_hours": 3200.0,
        "hourly_rate_min": 32.0,
        "hourly_rate_max": 42.0,
        "docs_verified": True,
        "hire_date": "2021-03-01",
        "available_from": "2026-04-10",
        "ops_notes": "OSP traveler. Current rural buildout ending early April. Book next ASAP.",
        "skills": [
            _skill("osp-construction", "Intermediate", 250.0, "2026-03-15"),
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-03-15"),
            _skill("aerial-lift", "Intermediate", 150.0, "2026-03-10"),
            _skill("otdr-testing", "Apprentice", 70.0, "2026-02-28"),
            _skill("confined-space", "Apprentice", 50.0, "2026-01-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-08-15", None, "Active", "CFOT-2021-10456"),
            _cert("osha-10", "2021-05-01", None, "Active"),
            _cert("first-aid-cpr", "2025-05-15", "2027-05-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "AT&T Cleared", "badge_type": "client"},
        ],
    },
    {
        "first_name": "Ricardo",
        "last_name": "Flores",
        "email": "ricardo.flores@deployable.demo",
        "phone": "555-0136",
        "home_base_city": "Sacramento",
        "home_base_state": "CA",
        "approved_regions": ["CA", "NV", "OR", "WA", "AZ", "UT", "CO", "ID"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 1200,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "traveling_tech",
        "years_experience": 9.0,
        "total_project_count": 26,
        "total_approved_hours": 6000.0,
        "hourly_rate_min": 40.0,
        "hourly_rate_max": 52.0,
        "docs_verified": True,
        "hire_date": "2017-08-01",
        "available_from": "2026-03-21",
        "ops_notes": "West coast traveler. Will fly to jobs. DAS/wireless specialist on the road.",
        "skills": [
            _skill("das-installation", "Advanced", 2200.0, "2026-02-20"),
            _skill("small-cell", "Advanced", 1400.0, "2026-02-15"),
            _skill("rf-testing", "Intermediate", 250.0, "2026-02-10"),
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-01-30"),
            _skill("cable-pathway", "Intermediate", 180.0, "2026-01-20"),
            _skill("aerial-lift", "Intermediate", 120.0, "2025-12-15"),
        ],
        "certifications": [
            _cert("foa-cfot", "2018-03-10", None, "Active", "CFOT-2018-7102"),
            _cert("osha-30", "2019-11-01", None, "Active"),
            _cert("first-aid-cpr", "2025-07-01", "2027-07-01", "Active"),
            _cert("eta-foi", "2023-05-15", "2025-05-15", "Expired"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "T-Mobile Site Access", "badge_type": "site"},
            {"badge_name": "Crown Castle Authorized", "badge_type": "client"},
        ],
    },
    {
        "first_name": "Monica",
        "last_name": "Sullivan",
        "email": "monica.sullivan@deployable.demo",
        "phone": "555-0137",
        "home_base_city": "Salt Lake City",
        "home_base_state": "UT",
        "approved_regions": ["UT", "CO", "WY", "ID", "MT", "NV", "AZ", "NM"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 800,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "traveling_tech",
        "years_experience": 6.0,
        "total_project_count": 17,
        "total_approved_hours": 3800.0,
        "hourly_rate_min": 34.0,
        "hourly_rate_max": 44.0,
        "docs_verified": True,
        "hire_date": "2020-05-15",
        "ops_notes": "Mountain West specialist. Comfortable with rural/remote sites. Great attitude.",
        "skills": [
            _skill("osp-construction", "Intermediate", 250.0, "2026-03-12"),
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-03-10"),
            _skill("fiber-termination", "Intermediate", 150.0, "2026-03-05"),
            _skill("aerial-lift", "Intermediate", 100.0, "2026-02-28"),
            _skill("otdr-testing", "Intermediate", 120.0, "2026-02-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-01-10", None, "Active", "CFOT-2021-9001"),
            _cert("osha-10", "2020-07-15", None, "Active"),
            _cert("first-aid-cpr", "2025-11-01", "2027-11-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Terrence",
        "last_name": "Grant",
        "email": "terrence.grant@deployable.demo",
        "phone": "555-0138",
        "home_base_city": "Jacksonville",
        "home_base_state": "FL",
        "approved_regions": ["FL", "GA", "SC", "NC", "VA", "AL", "MS", "LA", "TX"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 1000,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Missing Docs",
        "archetype": "traveling_tech",
        "years_experience": 4.0,
        "total_project_count": 11,
        "total_approved_hours": 2600.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": False,
        "hire_date": "2022-04-01",
        "available_from": "2026-04-01",
        "ops_notes": "Willing traveler but vehicle insurance lapsed. Needs to renew before next deploy.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 180.0, "2026-01-30"),
            _skill("osp-construction", "Intermediate", 160.0, "2026-01-25"),
            _skill("cat6-termination", "Intermediate", 120.0, "2026-01-20"),
            _skill("aerial-lift", "Intermediate", 80.0, "2025-12-15"),
            _skill("cable-pathway", "Apprentice", 60.0, "2025-12-01"),
        ],
        "certifications": [
            _cert("foa-cfot", "2022-10-01", None, "Active", "CFOT-2022-14521"),
            _cert("osha-10", "2022-06-15", None, "Active"),
            _cert("first-aid-cpr", "2024-08-01", "2026-08-01", "Active"),
        ],
        "documents": [
            _doc("background_check"),
            _doc("drivers_license"),
            _doc("w9"),
            _doc("drug_screen"),
            _doc("safety_training_record"),
            _doc("vehicle_insurance", "Expired"),
        ],
        "site_badges": [],
    },
    {
        "first_name": "Priya",
        "last_name": "Sharma",
        "email": "priya.sharma@deployable.demo",
        "phone": "555-0139",
        "home_base_city": "Raleigh",
        "home_base_state": "NC",
        "approved_regions": ["NC", "SC", "VA", "GA", "TN", "MD", "DC", "PA", "NJ", "NY"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 900,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "traveling_tech",
        "years_experience": 5.5,
        "total_project_count": 16,
        "total_approved_hours": 3600.0,
        "hourly_rate_min": 35.0,
        "hourly_rate_max": 45.0,
        "docs_verified": True,
        "hire_date": "2020-10-01",
        "ops_notes": "East coast DC specialist. Excellent attention to detail on rack work. Multi-state cleared.",
        "skills": [
            _skill("rack-and-stack", "Intermediate", 250.0, "2026-03-18"),
            _skill("cross-connect", "Intermediate", 180.0, "2026-03-15"),
            _skill("power-distribution", "Apprentice", 80.0, "2026-03-10"),
            _skill("hot-cold-aisle", "Apprentice", 60.0, "2026-02-28"),
            _skill("cable-cert-testing", "Intermediate", 140.0, "2026-03-05"),
            _skill("fiber-termination", "Intermediate", 120.0, "2026-02-20"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2023-09-01", "2026-09-01", "Active", "BICSI-I2-91088"),
            _cert("osha-10", "2020-12-15", None, "Active"),
            _cert("first-aid-cpr", "2025-04-01", "2027-04-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "QTS Cleared", "badge_type": "site"},
            {"badge_name": "Digital Realty Authorized", "badge_type": "site"},
        ],
    },
    {
        "first_name": "Jake",
        "last_name": "Larson",
        "email": "jake.larson@deployable.demo",
        "phone": "555-0140",
        "home_base_city": "Milwaukee",
        "home_base_state": "WI",
        "approved_regions": ["WI", "MN", "IA", "IL", "IN", "MI", "OH", "ND", "SD", "NE"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 800,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "traveling_tech",
        "years_experience": 7.5,
        "total_project_count": 21,
        "total_approved_hours": 4800.0,
        "hourly_rate_min": 36.0,
        "hourly_rate_max": 46.0,
        "docs_verified": True,
        "hire_date": "2018-10-15",
        "available_from": "2026-03-20",
        "ops_notes": "Midwest road warrior. OSP specialist. Handles extreme cold weather builds well.",
        "skills": [
            _skill("osp-construction", "Advanced", 2000.0, "2026-02-28"),
            _skill("fiber-splicing", "Advanced", 1400.0, "2026-02-25"),
            _skill("aerial-lift", "Advanced", 400.0, "2026-02-20"),
            _skill("confined-space", "Intermediate", 100.0, "2026-01-15"),
            _skill("otdr-testing", "Intermediate", 200.0, "2026-02-10"),
            _skill("fiber-route-design", "Apprentice", 80.0, "2025-12-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2019-04-15", None, "Active", "CFOT-2019-8456"),
            _cert("foa-cfos-s", "2020-08-10", None, "Active"),
            _cert("osha-30", "2021-01-15", None, "Active"),
            _cert("first-aid-cpr", "2025-06-01", "2027-06-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Lumen Cleared", "badge_type": "client"},
            {"badge_name": "Frontier Authorized", "badge_type": "client"},
        ],
    },
    {
        "first_name": "Cassandra",
        "last_name": "Bell",
        "email": "cassandra.bell@deployable.demo",
        "phone": "555-0141",
        "home_base_city": "Albuquerque",
        "home_base_state": "NM",
        "approved_regions": ["NM", "AZ", "TX", "CO", "UT", "NV", "CA"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 900,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "traveling_tech",
        "years_experience": 4.5,
        "total_project_count": 13,
        "total_approved_hours": 3000.0,
        "hourly_rate_min": 32.0,
        "hourly_rate_max": 42.0,
        "docs_verified": True,
        "hire_date": "2021-09-01",
        "ops_notes": "Southwest traveler. Strong in fiber and copper. Adaptable to different project types.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-03-12"),
            _skill("fiber-termination", "Intermediate", 150.0, "2026-03-08"),
            _skill("cat6-termination", "Intermediate", 180.0, "2026-03-05"),
            _skill("osp-construction", "Intermediate", 140.0, "2026-02-28"),
            _skill("cable-pathway", "Intermediate", 120.0, "2026-02-20"),
            _skill("aerial-lift", "Apprentice", 60.0, "2026-01-15"),
        ],
        "certifications": [
            _cert("foa-cfot", "2022-02-15", None, "Active", "CFOT-2022-11890"),
            _cert("osha-10", "2021-11-01", None, "Active"),
            _cert("first-aid-cpr", "2025-10-15", "2027-10-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },

    # =====================================================================
    # 43-50: LOCAL-ONLY TECHS — prefer to stay near home base
    # =====================================================================
    {
        "first_name": "Michael",
        "last_name": "Tran",
        "email": "michael.tran@deployable.demo",
        "phone": "555-0142",
        "home_base_city": "San Francisco",
        "home_base_state": "CA",
        "approved_regions": ["CA"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 50,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "local_only",
        "years_experience": 6.0,
        "total_project_count": 12,
        "total_approved_hours": 3200.0,
        "hourly_rate_min": 38.0,
        "hourly_rate_max": 48.0,
        "docs_verified": True,
        "hire_date": "2020-02-01",
        "ops_notes": "SF Bay Area only. Excellent DC tech but won't travel. Family commitment.",
        "skills": [
            _skill("rack-and-stack", "Advanced", 1400.0, "2026-03-18"),
            _skill("cross-connect", "Intermediate", 250.0, "2026-03-15"),
            _skill("power-distribution", "Intermediate", 200.0, "2026-03-10"),
            _skill("hot-cold-aisle", "Intermediate", 180.0, "2026-02-28"),
            _skill("cable-cert-testing", "Intermediate", 120.0, "2026-03-05"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2023-04-01", "2026-04-01", "Active", "BICSI-I2-87654"),
            _cert("osha-10", "2020-04-15", None, "Active"),
            _cert("nfpa-70e", "2025-05-01", "2026-05-01", "Active"),
            _cert("first-aid-cpr", "2025-03-01", "2027-03-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Equinix SV Authorized", "badge_type": "site"},
        ],
    },
    {
        "first_name": "Heather",
        "last_name": "Wood",
        "email": "heather.wood@deployable.demo",
        "phone": "555-0143",
        "home_base_city": "Ashburn",
        "home_base_state": "VA",
        "approved_regions": ["VA", "MD", "DC"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 40,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "local_only",
        "years_experience": 8.0,
        "total_project_count": 20,
        "total_approved_hours": 4800.0,
        "hourly_rate_min": 42.0,
        "hourly_rate_max": 54.0,
        "docs_verified": True,
        "hire_date": "2018-04-01",
        "ops_notes": "Data Center Alley specialist. Lives in Ashburn. All major DC operators know her.",
        "skills": [
            _skill("rack-and-stack", "Advanced", 2200.0, "2026-03-18"),
            _skill("cross-connect", "Advanced", 1600.0, "2026-03-15"),
            _skill("hot-cold-aisle", "Advanced", 800.0, "2026-03-10"),
            _skill("power-distribution", "Intermediate", 250.0, "2026-02-28"),
            _skill("fiber-termination", "Intermediate", 200.0, "2026-02-20"),
            _skill("cable-cert-testing", "Advanced", 600.0, "2026-03-12"),
        ],
        "certifications": [
            _cert("bicsi-tech", "2024-08-01", "2027-08-01", "Active", "BICSI-I2-98765"),
            _cert("osha-10", "2018-06-15", None, "Active"),
            _cert("nfpa-70e", "2025-09-01", "2026-09-01", "Active"),
            _cert("first-aid-cpr", "2025-06-15", "2027-06-15", "Active"),
            _cert("comptia-network-plus", "2024-01-10", "2027-01-10", "Active", "NP-2024-12345"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "AWS Cleared", "badge_type": "client"},
            {"badge_name": "Equinix DC Authorized", "badge_type": "site"},
            {"badge_name": "Digital Realty Authorized", "badge_type": "site"},
            {"badge_name": "5000+ Hours", "badge_type": "milestone"},
        ],
    },
    {
        "first_name": "Gregory",
        "last_name": "Simmons",
        "email": "gregory.simmons@deployable.demo",
        "phone": "555-0144",
        "home_base_city": "Newark",
        "home_base_state": "NJ",
        "approved_regions": ["NJ", "NY"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 30,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "local_only",
        "years_experience": 5.0,
        "total_project_count": 10,
        "total_approved_hours": 2800.0,
        "hourly_rate_min": 35.0,
        "hourly_rate_max": 45.0,
        "docs_verified": True,
        "hire_date": "2021-02-15",
        "available_from": "2026-03-22",
        "ops_notes": "NYC metro only. Good fiber tech. Reliable for urban/campus builds.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 250.0, "2026-02-25"),
            _skill("fiber-termination", "Intermediate", 200.0, "2026-02-20"),
            _skill("cat6-termination", "Intermediate", 180.0, "2026-02-15"),
            _skill("cable-pathway", "Intermediate", 150.0, "2026-02-10"),
            _skill("rack-and-stack", "Apprentice", 70.0, "2025-12-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-08-20", None, "Active", "CFOT-2021-10234"),
            _cert("osha-10", "2021-04-15", None, "Active"),
            _cert("first-aid-cpr", "2025-09-01", "2027-09-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Yolanda",
        "last_name": "Morales",
        "email": "yolanda.morales@deployable.demo",
        "phone": "555-0145",
        "home_base_city": "Los Angeles",
        "home_base_state": "CA",
        "approved_regions": ["CA"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 60,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "local_only",
        "years_experience": 4.0,
        "total_project_count": 9,
        "total_approved_hours": 2200.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": True,
        "hire_date": "2022-03-01",
        "ops_notes": "LA basin only. DAS/small cell specialist. Bilingual English/Spanish.",
        "skills": [
            _skill("das-installation", "Intermediate", 200.0, "2026-03-15"),
            _skill("small-cell", "Intermediate", 150.0, "2026-03-10"),
            _skill("rf-testing", "Apprentice", 60.0, "2026-02-28"),
            _skill("cable-pathway", "Intermediate", 120.0, "2026-02-20"),
            _skill("fiber-termination", "Apprentice", 70.0, "2026-01-30"),
        ],
        "certifications": [
            _cert("osha-10", "2022-05-15", None, "Active"),
            _cert("first-aid-cpr", "2025-08-01", "2027-08-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "T-Mobile Site Access", "badge_type": "site"},
        ],
    },
    {
        "first_name": "Dennis",
        "last_name": "Parker",
        "email": "dennis.parker@deployable.demo",
        "phone": "555-0146",
        "home_base_city": "Chicago",
        "home_base_state": "IL",
        "approved_regions": ["IL"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 40,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "local_only",
        "years_experience": 7.0,
        "total_project_count": 16,
        "total_approved_hours": 3800.0,
        "hourly_rate_min": 36.0,
        "hourly_rate_max": 46.0,
        "docs_verified": True,
        "hire_date": "2019-06-01",
        "available_from": "2026-03-20",
        "ops_notes": "Chicago metro only. Experienced fiber and copper. Prefers enterprise campus work.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 250.0, "2026-02-28"),
            _skill("cat6-termination", "Advanced", 600.0, "2026-03-01"),
            _skill("cable-pathway", "Advanced", 500.0, "2026-02-25"),
            _skill("cable-cert-testing", "Intermediate", 200.0, "2026-02-20"),
            _skill("fiber-termination", "Intermediate", 180.0, "2026-02-15"),
            _skill("rack-and-stack", "Apprentice", 80.0, "2025-11-30"),
        ],
        "certifications": [
            _cert("foa-cfot", "2020-02-10", None, "Active", "CFOT-2020-12567"),
            _cert("bicsi-tech", "2023-07-01", "2026-07-01", "Active", "BICSI-I2-89012"),
            _cert("osha-10", "2019-08-15", None, "Active"),
            _cert("first-aid-cpr", "2025-01-20", "2027-01-20", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Tanya",
        "last_name": "Volkov",
        "email": "tanya.volkov@deployable.demo",
        "phone": "555-0147",
        "home_base_city": "Houston",
        "home_base_state": "TX",
        "approved_regions": ["TX"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 50,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "local_only",
        "years_experience": 3.0,
        "total_project_count": 7,
        "total_approved_hours": 1600.0,
        "hourly_rate_min": 28.0,
        "hourly_rate_max": 36.0,
        "docs_verified": True,
        "hire_date": "2023-04-01",
        "ops_notes": "Houston area only. Growing DC tech. Currently on a long-term rack & stack project.",
        "skills": [
            _skill("rack-and-stack", "Intermediate", 140.0, "2026-03-18"),
            _skill("cross-connect", "Apprentice", 60.0, "2026-03-10"),
            _skill("cable-pathway", "Intermediate", 100.0, "2026-02-28"),
            _skill("cat6-termination", "Apprentice", 80.0, "2026-02-15"),
        ],
        "certifications": [
            _cert("osha-10", "2023-06-15", None, "Active"),
            _cert("first-aid-cpr", "2025-04-01", "2027-04-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Andre",
        "last_name": "Benson",
        "email": "andre.benson@deployable.demo",
        "phone": "555-0148",
        "home_base_city": "Hillsboro",
        "home_base_state": "OR",
        "approved_regions": ["OR"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 30,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Missing Cert",
        "archetype": "local_only",
        "years_experience": 3.5,
        "total_project_count": 8,
        "total_approved_hours": 2000.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": True,
        "hire_date": "2022-09-15",
        "available_from": "2026-04-01",
        "ops_notes": "Portland/Hillsboro area DC tech. NFPA 70E expired — needed for Intel jobs. Scheduling renewal.",
        "skills": [
            _skill("rack-and-stack", "Intermediate", 180.0, "2026-02-10"),
            _skill("power-distribution", "Intermediate", 120.0, "2026-02-05"),
            _skill("hot-cold-aisle", "Apprentice", 60.0, "2026-01-20"),
            _skill("cross-connect", "Apprentice", 50.0, "2026-01-15"),
            _skill("cable-cert-testing", "Apprentice", 40.0, "2026-01-10"),
        ],
        "certifications": [
            _cert("osha-10", "2022-11-01", None, "Active"),
            _cert("nfpa-70e", "2024-12-01", "2025-12-01", "Expired"),
            _cert("first-aid-cpr", "2025-02-15", "2027-02-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Crystal",
        "last_name": "Adams",
        "email": "crystal.adams@deployable.demo",
        "phone": "555-0149",
        "home_base_city": "Virginia Beach",
        "home_base_state": "VA",
        "approved_regions": ["VA", "NC"],
        "willing_to_travel": False,
        "max_travel_radius_miles": 60,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "local_only",
        "years_experience": 5.0,
        "total_project_count": 11,
        "total_approved_hours": 2800.0,
        "hourly_rate_min": 32.0,
        "hourly_rate_max": 42.0,
        "docs_verified": True,
        "hire_date": "2021-04-15",
        "ops_notes": "Hampton Roads / Virginia Beach area. OSP and campus fiber. Solid performer.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 250.0, "2026-03-15"),
            _skill("fiber-termination", "Intermediate", 180.0, "2026-03-10"),
            _skill("osp-construction", "Intermediate", 160.0, "2026-03-05"),
            _skill("otdr-testing", "Intermediate", 120.0, "2026-02-28"),
            _skill("cable-pathway", "Apprentice", 70.0, "2026-02-15"),
        ],
        "certifications": [
            _cert("foa-cfot", "2021-10-01", None, "Active", "CFOT-2021-10678"),
            _cert("osha-10", "2021-06-15", None, "Active"),
            _cert("first-aid-cpr", "2025-07-01", "2027-07-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Navy Base Cleared", "badge_type": "site"},
        ],
    },

    # =====================================================================
    # 51-55: SPECIAL CASES — edge cases for testing system logic
    # =====================================================================
    {
        "first_name": "Raymond",
        "last_name": "Torres",
        "email": "raymond.torres@deployable.demo",
        "phone": "555-0150",
        "home_base_city": "Detroit",
        "home_base_state": "MI",
        "approved_regions": ["MI", "OH", "IN"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Deployed",
        "deployability_status": "Inactive",
        "deployability_locked": True,
        "archetype": "generalist",
        "years_experience": 6.0,
        "total_project_count": 15,
        "total_approved_hours": 3400.0,
        "hourly_rate_min": 34.0,
        "hourly_rate_max": 44.0,
        "docs_verified": True,
        "hire_date": "2020-01-15",
        "ops_notes": "On medical leave since Feb 2026. Status locked to Inactive by ops. Expected return May 2026.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 200.0, "2026-01-30"),
            _skill("cat6-termination", "Intermediate", 180.0, "2026-01-25"),
            _skill("cable-pathway", "Intermediate", 150.0, "2026-01-20"),
            _skill("rack-and-stack", "Apprentice", 60.0, "2025-12-10"),
            _skill("osp-construction", "Intermediate", 120.0, "2025-11-30"),
        ],
        "certifications": [
            _cert("foa-cfot", "2020-07-10", None, "Active", "CFOT-2020-12890"),
            _cert("osha-10", "2020-03-15", None, "Active"),
            _cert("first-aid-cpr", "2024-09-01", "2026-09-01", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Vanessa",
        "last_name": "Cruz",
        "email": "vanessa.cruz@deployable.demo",
        "phone": "555-0151",
        "home_base_city": "Orlando",
        "home_base_state": "FL",
        "approved_regions": ["FL", "GA"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 250,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Inactive",
        "deployability_locked": True,
        "archetype": "generalist",
        "years_experience": 3.0,
        "total_project_count": 6,
        "total_approved_hours": 1400.0,
        "hourly_rate_min": 26.0,
        "hourly_rate_max": 34.0,
        "docs_verified": False,
        "hire_date": "2023-06-01",
        "ops_notes": "Inactive — failed drug screen. Under review. Do not assign.",
        "skills": [
            _skill("fiber-splicing", "Apprentice", 80.0, "2025-10-15"),
            _skill("cat6-termination", "Intermediate", 120.0, "2025-10-10"),
            _skill("cable-pathway", "Apprentice", 60.0, "2025-09-30"),
        ],
        "certifications": [
            _cert("osha-10", "2023-08-15", None, "Active"),
        ],
        "documents": [
            _doc("background_check"),
            _doc("drivers_license"),
            _doc("w9"),
            _doc("drug_screen", "Expired"),
            _doc("safety_training_record"),
            _doc("vehicle_insurance"),
        ],
        "site_badges": [],
    },
    {
        "first_name": "Nathan",
        "last_name": "Price",
        "email": "nathan.price@deployable.demo",
        "phone": "555-0152",
        "home_base_city": "Austin",
        "home_base_state": "TX",
        "approved_regions": ["TX", "OK", "LA", "AR", "NM", "CO"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 600,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "traveling_tech",
        "years_experience": 10.0,
        "total_project_count": 30,
        "total_approved_hours": 7000.0,
        "hourly_rate_min": 42.0,
        "hourly_rate_max": 55.0,
        "docs_verified": True,
        "hire_date": "2016-05-01",
        "ops_notes": "Dual-skilled: fiber + DC. One of our most versatile techs. Currently on major buildout.",
        "skills": [
            _skill("fiber-splicing", "Advanced", 2800.0, "2026-03-18"),
            _skill("rack-and-stack", "Advanced", 1800.0, "2026-03-15"),
            _skill("otdr-testing", "Advanced", 800.0, "2026-03-10"),
            _skill("cross-connect", "Intermediate", 250.0, "2026-03-05"),
            _skill("power-distribution", "Intermediate", 200.0, "2026-02-28"),
            _skill("osp-construction", "Intermediate", 250.0, "2026-02-15"),
            _skill("project-coordination", "Intermediate", 180.0, "2026-03-18"),
        ],
        "certifications": [
            _cert("foa-cfot", "2017-01-15", None, "Active", "CFOT-2017-5890"),
            _cert("foa-cfos-s", "2018-05-20", None, "Active"),
            _cert("foa-cfos-t", "2019-03-10", None, "Active"),
            _cert("bicsi-tech", "2023-12-01", "2026-12-01", "Active", "BICSI-I2-94321"),
            _cert("osha-30", "2020-08-15", None, "Active"),
            _cert("nfpa-70e", "2025-04-01", "2026-04-01", "Active"),
            _cert("first-aid-cpr", "2025-10-01", "2027-10-01", "Active"),
            _cert("corning-certified", "2024-06-15", "2026-06-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "Google DC Authorized", "badge_type": "site"},
            {"badge_name": "Meta DC Cleared", "badge_type": "client"},
            {"badge_name": "AT&T Cleared", "badge_type": "client"},
            {"badge_name": "7000+ Hours", "badge_type": "milestone"},
        ],
    },
    {
        "first_name": "Alicia",
        "last_name": "Whitfield",
        "email": "alicia.whitfield@deployable.demo",
        "phone": "555-0153",
        "home_base_city": "Richmond",
        "home_base_state": "VA",
        "approved_regions": ["VA", "MD", "DC", "NC", "WV"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 300,
        "career_stage": "Training Completed",
        "deployability_status": "Missing Docs",
        "archetype": "apprentice",
        "years_experience": 1.0,
        "total_project_count": 2,
        "total_approved_hours": 500.0,
        "hourly_rate_min": 22.0,
        "hourly_rate_max": 28.0,
        "docs_verified": False,
        "hire_date": "2025-03-01",
        "available_from": "2026-04-01",
        "ops_notes": "Training completed but background check still pending review. Hold for clearance.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 120.0, "2026-02-28"),
            _skill("fiber-termination", "Apprentice", 90.0, "2026-02-25"),
            _skill("otdr-testing", "Apprentice", 50.0, "2026-02-20"),
            _skill("cat6-termination", "Apprentice", 70.0, "2026-02-15"),
            _skill("cable-pathway", "Apprentice", 55.0, "2026-02-10"),
        ],
        "certifications": [
            _cert("foa-cfot", "2026-01-20", None, "Active", "CFOT-2026-18001"),
            _cert("osha-10", "2025-05-15", None, "Active"),
            _cert("first-aid-cpr", "2025-06-01", "2027-06-01", "Active"),
        ],
        "documents": [
            _doc("background_check", "Pending Review"),
            _doc("drivers_license"),
            _doc("w9"),
            _doc("drug_screen"),
            _doc("safety_training_record"),
            _doc("vehicle_insurance"),
        ],
        "site_badges": [],
    },
    {
        "first_name": "Warren",
        "last_name": "Blake",
        "email": "warren.blake@deployable.demo",
        "phone": "555-0154",
        "home_base_city": "Las Vegas",
        "home_base_state": "NV",
        "approved_regions": ["NV", "AZ", "CA", "UT"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 400,
        "career_stage": "Awaiting Assignment",
        "deployability_status": "Ready Now",
        "archetype": "generalist",
        "years_experience": 4.0,
        "total_project_count": 10,
        "total_approved_hours": 2400.0,
        "hourly_rate_min": 30.0,
        "hourly_rate_max": 40.0,
        "docs_verified": True,
        "hire_date": "2022-05-15",
        "available_from": "2026-03-19",
        "ops_notes": "Available today. Well-rounded generalist. Good for quick-start projects.",
        "skills": [
            _skill("fiber-splicing", "Intermediate", 160.0, "2026-03-05"),
            _skill("fiber-termination", "Intermediate", 120.0, "2026-03-01"),
            _skill("rack-and-stack", "Intermediate", 140.0, "2026-02-25"),
            _skill("cat6-termination", "Intermediate", 130.0, "2026-02-20"),
            _skill("cable-pathway", "Intermediate", 110.0, "2026-02-15"),
            _skill("otdr-testing", "Apprentice", 50.0, "2026-01-30"),
        ],
        "certifications": [
            _cert("foa-cfot", "2022-11-01", None, "Active", "CFOT-2022-14890"),
            _cert("osha-10", "2022-07-15", None, "Active"),
            _cert("first-aid-cpr", "2025-11-15", "2027-11-15", "Active"),
            _cert("eta-foi", "2023-08-01", "2025-08-01", "Expired"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [],
    },
    {
        "first_name": "Russell",
        "last_name": "Chang",
        "email": "russell.chang@deployable.demo",
        "phone": "555-0155",
        "home_base_city": "San Diego",
        "home_base_state": "CA",
        "approved_regions": ["CA", "AZ", "NV"],
        "willing_to_travel": True,
        "max_travel_radius_miles": 400,
        "career_stage": "Deployed",
        "deployability_status": "Currently Assigned",
        "archetype": "senior_specialist",
        "years_experience": 11.0,
        "total_project_count": 30,
        "total_approved_hours": 7200.0,
        "hourly_rate_min": 44.0,
        "hourly_rate_max": 56.0,
        "docs_verified": True,
        "hire_date": "2015-06-01",
        "ops_notes": "OSP design/build lead. Has CDL and flagger cert. Can drive cable trucks. CommScope certified.",
        "skills": [
            _skill("osp-construction", "Advanced", 3000.0, "2026-03-18"),
            _skill("fiber-splicing", "Advanced", 1800.0, "2026-03-15"),
            _skill("fiber-route-design", "Advanced", 800.0, "2026-03-10"),
            _skill("otdr-testing", "Intermediate", 250.0, "2026-02-28"),
            _skill("aerial-lift", "Advanced", 600.0, "2026-03-12"),
            _skill("confined-space", "Intermediate", 150.0, "2026-02-20"),
        ],
        "certifications": [
            _cert("foa-cfot", "2016-02-10", None, "Active", "CFOT-2016-5201"),
            _cert("foa-cfos-s", "2017-08-15", None, "Active"),
            _cert("osha-30", "2018-11-01", None, "Active"),
            _cert("first-aid-cpr", "2025-05-01", "2027-05-01", "Active"),
            _cert("corning-certified", "2024-09-15", "2026-09-15", "Active"),
        ],
        "documents": ALL_DOCS_VERIFIED,
        "site_badges": [
            {"badge_name": "AT&T Cleared", "badge_type": "client"},
            {"badge_name": "Lumen Cleared", "badge_type": "client"},
            {"badge_name": "5000+ Hours", "badge_type": "milestone"},
        ],
    },
]

# ── Summary Statistics ───────────────────────────────────────────────────────
# Total technicians: 55
#
# By deployability_status:
#   Ready Now:          14
#   Currently Assigned: 20
#   In Training:         8
#   Rolling Off Soon:    3
#   Missing Cert:        3
#   Missing Docs:        5
#   Inactive:            2
#
# By archetype:
#   senior_specialist:   9  (includes Russell Chang)
#   generalist:         15
#   apprentice:         12
#   traveling_tech:     11
#   local_only:          8
#
# All 18 skills from taxonomy are referenced across technicians.
# 10 of 14 certifications are actively used in technician records.
