import type { Recommendation, PreferenceRule, ActivityLogEntry } from '@/types'

// ============================================================
// Agent Inbox Seed Data
// ============================================================

export const seedPendingRecommendations: Recommendation[] = [
  {
    id: 'rec-001',
    type: 'staffing',
    target_id: 'tech-012',
    target_name: 'Marcus Rivera',
    scorecard: {
      skill_match: { score: 92, status: 'pass', detail: 'Advanced fiber splicing + OTDR testing' },
      availability: { score: 100, status: 'pass', detail: 'Available immediately, no current assignment' },
      certification: { score: 85, status: 'pass', detail: 'CFOT active, OSHA 10 active' },
      location: { score: 70, status: 'warn', detail: 'Home base Dallas, project in Phoenix — 900mi travel' },
      experience: { score: 88, status: 'pass', detail: '3 prior data center builds, 1,200+ field hours' },
      overall_score: 87,
    },
    explanation: 'Marcus Rivera is the top candidate for Lead Splicer on the Phoenix Metro Fiber Build. His advanced splicing skills and CFOT certification exceed role requirements. Minor travel distance from Dallas, but he has approved AZ as a work region. Three prior data center builds demonstrate relevant experience. Recommended with high confidence.',
    status: 'Pending',
    agent: 'staffing_agent',
    created_at: '2026-03-19T08:15:00Z',
    context: { project_id: 'proj-003', project_name: 'Phoenix Metro Fiber Build', role_name: 'Lead Splicer' },
  },
  {
    id: 'rec-002',
    type: 'staffing',
    target_id: 'tech-007',
    target_name: 'Sarah Chen',
    scorecard: {
      skill_match: { score: 78, status: 'pass', detail: 'Intermediate splicing, Advanced OTDR' },
      availability: { score: 100, status: 'pass', detail: 'Rolling off current project in 5 days' },
      certification: { score: 90, status: 'pass', detail: 'All required certs active' },
      location: { score: 95, status: 'pass', detail: 'Home base Phoenix — local to project' },
      experience: { score: 65, status: 'warn', detail: '1 prior fiber build, 480 field hours' },
      overall_score: 82,
    },
    explanation: 'Sarah Chen ranks #2 for Lead Splicer on Phoenix Metro. Strong local advantage and excellent certifications, but fewer field hours than ideal. Her OTDR skills are advanced which partially compensates. Consider if project timeline allows her continued development.',
    status: 'Pending',
    agent: 'staffing_agent',
    created_at: '2026-03-19T08:15:00Z',
    context: { project_id: 'proj-003', project_name: 'Phoenix Metro Fiber Build', role_name: 'Lead Splicer' },
  },
  {
    id: 'rec-003',
    type: 'cert_renewal',
    target_id: 'tech-019',
    target_name: 'James Mitchell',
    scorecard: {
      skill_match: { score: 0, status: 'pass', detail: 'N/A for cert renewal' },
      availability: { score: 0, status: 'pass', detail: 'N/A for cert renewal' },
      certification: { score: 30, status: 'fail', detail: 'OSHA 30 expires in 14 days' },
      location: { score: 0, status: 'pass', detail: 'N/A for cert renewal' },
      experience: { score: 0, status: 'pass', detail: 'N/A for cert renewal' },
      overall_score: 30,
    },
    explanation: "James Mitchell's OSHA 30 certification expires on April 2, 2026. He is currently assigned to the Atlanta Backbone project which requires OSHA 30. Recommend scheduling renewal training immediately to avoid deployment gap.",
    status: 'Pending',
    agent: 'cert_monitor_agent',
    created_at: '2026-03-18T22:00:00Z',
    context: { cert_name: 'OSHA 30', expiry_date: '2026-04-02' },
  },
  {
    id: 'rec-004',
    type: 'training',
    target_id: 'tech-031',
    target_name: 'David Park',
    scorecard: {
      skill_match: { score: 0, status: 'pass', detail: 'N/A' },
      availability: { score: 0, status: 'pass', detail: 'N/A' },
      certification: { score: 0, status: 'pass', detail: 'N/A' },
      location: { score: 0, status: 'pass', detail: 'N/A' },
      experience: { score: 55, status: 'warn', detail: '95 hours in fiber splicing, 5 hours from Intermediate' },
      overall_score: 55,
    },
    explanation: 'David Park has accumulated 95 approved hours in Fiber Splicing. At 100 hours he will auto-advance to Intermediate proficiency. Recommend prioritizing his next assignment to include splicing tasks to reach this milestone.',
    status: 'Pending',
    agent: 'training_agent',
    created_at: '2026-03-18T20:30:00Z',
    context: { skill_name: 'Fiber Splicing', current_hours: 95, threshold: 100 },
  },
  {
    id: 'rec-005',
    type: 'backfill',
    target_id: 'tech-044',
    target_name: 'Angela Torres',
    scorecard: {
      skill_match: { score: 85, status: 'pass', detail: 'Intermediate cable pulling, Advanced safety protocols' },
      availability: { score: 100, status: 'pass', detail: 'Unassigned, ready now' },
      certification: { score: 95, status: 'pass', detail: 'All certs current' },
      location: { score: 60, status: 'warn', detail: 'Home base Houston, project in Denver' },
      experience: { score: 72, status: 'pass', detail: '2 prior projects, 600+ hours' },
      overall_score: 78,
    },
    explanation: 'Backfill needed for Denver Campus Network project after Mike Johnson transitioned out. Angela Torres is the best available match with immediate availability and matching skill set. Travel from Houston is a consideration but within her approved regions.',
    status: 'Pending',
    agent: 'staffing_agent',
    created_at: '2026-03-18T16:45:00Z',
    context: { project_id: 'proj-006', project_name: 'Denver Campus Network', role_name: 'Cable Tech', reason: 'backfill' },
  },
  {
    id: 'rec-006',
    type: 'staffing',
    target_id: 'tech-015',
    target_name: 'Robert Kim',
    scorecard: {
      skill_match: { score: 88, status: 'pass', detail: 'Advanced network testing + fiber splicing' },
      availability: { score: 50, status: 'warn', detail: 'Available in 3 weeks — current project ending' },
      certification: { score: 100, status: 'pass', detail: 'CFOT, OSHA 30, BICSI certified' },
      location: { score: 90, status: 'pass', detail: 'Home base Seattle, project in Portland' },
      experience: { score: 95, status: 'pass', detail: '5 major builds, 2,400+ hours' },
      overall_score: 85,
    },
    explanation: 'Robert Kim is an excellent match for Senior Tech on Portland Distribution Hub. Top-tier certifications and extensive experience. Only caveat is 3-week availability gap — project start can accommodate this if planned now.',
    status: 'Pending',
    agent: 'staffing_agent',
    created_at: '2026-03-18T14:20:00Z',
    context: { project_id: 'proj-008', project_name: 'Portland Distribution Hub', role_name: 'Senior Tech' },
  },
  {
    id: 'rec-007',
    type: 'next_step',
    target_id: 'tech-023',
    target_name: 'Lisa Nguyen',
    scorecard: {
      skill_match: { score: 0, status: 'pass', detail: 'N/A' },
      availability: { score: 0, status: 'pass', detail: 'N/A' },
      certification: { score: 0, status: 'pass', detail: 'N/A' },
      location: { score: 0, status: 'pass', detail: 'N/A' },
      experience: { score: 0, status: 'pass', detail: 'N/A' },
      overall_score: 0,
    },
    explanation: "Lisa Nguyen completed training and all documentation is verified. She has 0 field assignments. Recommend moving her career stage to 'Awaiting Assignment' and including her in next staffing round.",
    status: 'Pending',
    agent: 'training_agent',
    created_at: '2026-03-18T12:00:00Z',
    context: { current_stage: 'Training Completed', suggested_stage: 'Awaiting Assignment' },
  },
]

// Helper to build a rule with all required fields
function makeRule(partial: Partial<PreferenceRule> & { id: string; rule_type: string; description: string }): PreferenceRule {
  return {
    template_type: 'custom',
    threshold: null,
    scope: 'global',
    scope_target_id: null,
    effect: 'demote',
    score_modifier: 0,
    priority: 0,
    parameters: {},
    status: 'active',
    active: true,
    rejection_id: null,
    source_recommendation_id: null,
    proposed_reason: null,
    created_by_type: 'ops',
    created_by_id: null,
    approved_by_id: null,
    approved_at: null,
    created_at: '2026-02-15T10:00:00Z',
    updated_at: null,
    type: partial.rule_type,
    ...partial,
  }
}

export const seedActiveRules: PreferenceRule[] = [
  makeRule({
    id: 'rule-001',
    rule_type: 'experience_threshold',
    template_type: 'experience_minimum',
    threshold: '500 hours',
    scope: 'Lead Splicer roles',
    effect: 'exclude',
    description: 'Exclude candidates with fewer than 500 field hours from Lead Splicer positions',
    parameters: { min_hours: 500 },
    score_modifier: -100,
    created_at: '2026-02-15T10:00:00Z',
  }),
  makeRule({
    id: 'rule-002',
    rule_type: 'cert_required',
    template_type: 'cert_required',
    threshold: 'CFOT Active',
    scope: 'All fiber splicing roles',
    effect: 'exclude',
    description: 'Require active CFOT certification for all fiber splicing role assignments',
    parameters: { cert_name: 'CFOT' },
    score_modifier: -100,
    created_at: '2026-02-10T09:00:00Z',
  }),
  makeRule({
    id: 'rule-003',
    rule_type: 'region_preference',
    template_type: 'region_preference',
    threshold: '500 miles',
    scope: 'global',
    effect: 'demote',
    description: 'Demote candidates whose home base is more than 500 miles from the project site',
    parameters: { max_distance_miles: 500 },
    score_modifier: -15,
    created_at: '2026-01-20T14:00:00Z',
  }),
  makeRule({
    id: 'rule-004',
    rule_type: 'skill_level_minimum',
    template_type: 'skill_minimum',
    threshold: 'Intermediate',
    scope: 'Data center projects',
    effect: 'exclude',
    description: 'Require at least Intermediate proficiency in primary skill for data center projects',
    parameters: { skill_name: 'primary', min_level: 'Intermediate' },
    score_modifier: -100,
    created_at: '2026-01-15T11:00:00Z',
  }),
  makeRule({
    id: 'rule-005',
    rule_type: 'recency',
    template_type: 'custom',
    threshold: '12 months',
    scope: 'Senior Tech roles',
    effect: 'demote',
    description: 'Demote candidates who have not had an active assignment in the last 12 months for Senior Tech roles',
    parameters: { max_inactive_months: 12 },
    score_modifier: -10,
    active: false,
    status: 'disabled',
    created_at: '2026-03-01T08:00:00Z',
  }),
  makeRule({
    id: 'rule-006',
    rule_type: 'project_history',
    template_type: 'project_history',
    threshold: '2 completed projects',
    scope: 'Lead roles',
    effect: 'exclude',
    description: 'Require at least 2 completed project assignments for any lead role',
    parameters: { min_completed_projects: 2 },
    score_modifier: -100,
    priority: 1,
    created_at: '2026-02-25T16:30:00Z',
  }),
]

export const seedProposedRules: PreferenceRule[] = [
  makeRule({
    id: 'rule-proposed-001',
    rule_type: 'cert_recency',
    template_type: 'cert_recency',
    threshold: '18 months',
    scope: 'global',
    effect: 'demote',
    description: 'Prefer technicians with certifications issued or renewed within 18 months for all assignments',
    parameters: { cert_name: 'CFOT', max_months: 18 },
    score_modifier: -8,
    status: 'proposed',
    active: false,
    created_by_type: 'agent',
    created_by_id: 'rejection_learning_agent',
    proposed_reason: 'Based on 3 rejections of technicians with stale CFOT certifications (>24 months old). Proposing a softer 18-month recency check as a demotion rather than hard filter.',
    rejection_id: 'rec-003',
    created_at: '2026-03-18T14:30:00Z',
  }),
  makeRule({
    id: 'rule-proposed-002',
    rule_type: 'availability_window',
    template_type: 'availability_window',
    threshold: '14 days',
    scope: 'global',
    effect: 'demote',
    description: 'Demote candidates who are not available within 14 days of the project start date',
    parameters: { max_days: 14 },
    score_modifier: -12,
    status: 'proposed',
    active: false,
    created_by_type: 'agent',
    created_by_id: 'rejection_learning_agent',
    proposed_reason: 'Analysis of 5 recent rejections shows ops consistently rejects candidates who are not available within 2 weeks of project start. Proposing a 14-day availability window demotion.',
    rejection_id: 'rec-007',
    created_at: '2026-03-17T09:15:00Z',
  }),
  makeRule({
    id: 'rule-proposed-003',
    rule_type: 'client_history_boost',
    template_type: 'client_history',
    threshold: '1 prior assignment',
    scope: 'client',
    scope_target_id: 'partner-verizon',
    effect: 'boost',
    description: 'Boost candidates with prior Verizon project experience for Verizon assignments',
    parameters: { client_name: 'Verizon', prefer_or_exclude: 'prefer' },
    score_modifier: 10,
    status: 'proposed',
    active: false,
    created_by_type: 'agent',
    created_by_id: 'rejection_learning_agent',
    proposed_reason: 'Verizon projects have 85% approval rate for returning technicians vs 45% for first-timers. Proposing a boost for repeat Verizon workers.',
    rejection_id: 'rec-012',
    created_at: '2026-03-16T16:45:00Z',
  }),
]

export const seedActivityLog: ActivityLogEntry[] = [
  {
    id: 'log-001',
    action: 'created',
    agent: 'staffing_agent',
    description: 'Generated 3 staffing recommendations for Phoenix Metro Fiber Build — Lead Splicer role',
    created_at: '2026-03-19T08:15:00Z',
    metadata: { project_id: 'proj-003', count: 3 },
  },
  {
    id: 'log-002',
    action: 'approved',
    agent: 'ops_user',
    description: 'Approved recommendation rec-010: Tom Bradley assigned to Atlanta Backbone — Fiber Tech',
    recommendation_id: 'rec-010',
    user_name: 'Alex Johnson',
    created_at: '2026-03-19T07:45:00Z',
  },
  {
    id: 'log-003',
    action: 'created',
    agent: 'cert_monitor_agent',
    description: "Generated cert renewal alert for James Mitchell — OSHA 30 expiring April 2",
    created_at: '2026-03-18T22:00:00Z',
    metadata: { technician_id: 'tech-019', cert_name: 'OSHA 30' },
  },
  {
    id: 'log-004',
    action: 'rejected',
    agent: 'ops_user',
    description: 'Rejected recommendation rec-009: Kevin Wu for Denver Campus Network — insufficient experience for lead role',
    recommendation_id: 'rec-009',
    user_name: 'Alex Johnson',
    created_at: '2026-03-18T19:30:00Z',
  },
  {
    id: 'log-005',
    action: 'rule_applied',
    agent: 'staffing_agent',
    description: 'Applied preference rule "Require CFOT for fiber roles" — excluded 4 candidates from Phoenix Metro staffing pool',
    created_at: '2026-03-18T18:00:00Z',
    metadata: { rule_id: 'rule-002', excluded_count: 4 },
  },
  {
    id: 'log-006',
    action: 'auto_advanced',
    agent: 'training_agent',
    description: 'Auto-advanced Maria Santos: Fiber Splicing Beginner → Intermediate (100 approved hours reached)',
    created_at: '2026-03-18T16:00:00Z',
    metadata: { technician_id: 'tech-028', skill: 'Fiber Splicing', new_level: 'Intermediate' },
  },
  {
    id: 'log-007',
    action: 'created',
    agent: 'staffing_agent',
    description: 'Generated backfill recommendation for Denver Campus Network after technician transition',
    created_at: '2026-03-18T16:45:00Z',
    metadata: { project_id: 'proj-006' },
  },
  {
    id: 'log-008',
    action: 'dismissed',
    agent: 'ops_user',
    description: 'Dismissed recommendation rec-008: Already handling via direct outreach',
    recommendation_id: 'rec-008',
    user_name: 'Sarah Palmer',
    created_at: '2026-03-18T15:20:00Z',
  },
  {
    id: 'log-009',
    action: 'approved',
    agent: 'ops_user',
    description: 'Approved recommendation rec-007: Lisa Nguyen career stage advanced to Awaiting Assignment',
    recommendation_id: 'rec-007',
    user_name: 'Alex Johnson',
    created_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'log-010',
    action: 'created',
    agent: 'training_agent',
    description: 'Nightly batch: Re-evaluated 52 technicians, refreshed 8 recommendations, removed 3 disqualified',
    created_at: '2026-03-18T03:00:00Z',
    metadata: { batch_run: true, evaluated: 52, refreshed: 8, removed: 3 },
  },
  {
    id: 'log-011',
    action: 'escalated',
    agent: 'cert_monitor_agent',
    description: 'Escalated: 2 technicians with certifications expiring within 30 days on active projects',
    created_at: '2026-03-17T22:00:00Z',
    metadata: { count: 2 },
  },
  {
    id: 'log-012',
    action: 'rule_applied',
    agent: 'staffing_agent',
    description: 'Applied preference rule "500hr minimum for Lead Splicer" — demoted 6 candidates in Portland Distribution Hub ranking',
    created_at: '2026-03-17T14:20:00Z',
    metadata: { rule_id: 'rule-001', demoted_count: 6 },
  },
]
