import type { Project } from '@/types'

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'Metro Fiber Expansion - Phoenix',
    status: 'Active',
    location_region: 'Arizona',
    location_city: 'Phoenix',
    start_date: '2026-01-15',
    end_date: '2026-06-30',
    partner_id: 'partner-001',
    partner_name: 'Lumen Technologies',
    description: 'Large-scale metro fiber deployment covering downtown Phoenix and surrounding suburbs. Includes aerial and underground installation across 45 miles.',
    roles: [
      {
        id: 'role-001',
        project_id: 'proj-001',
        role_name: 'Lead Splicer',
        skill_bundle: [
          { skill_name: 'Fiber Splicing', min_proficiency: 'Advanced' },
          { skill_name: 'OTDR Testing', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['CFOT', 'OSHA 10'],
        skill_weights: { 'Fiber Splicing': 0.6, 'OTDR Testing': 0.3, 'Safety': 0.1 },
        quantity: 2,
        filled: 2,
        hourly_rate: 55,
        per_diem: 85,
      },
      {
        id: 'role-002',
        project_id: 'proj-001',
        role_name: 'Fiber Technician',
        skill_bundle: [
          { skill_name: 'Fiber Splicing', min_proficiency: 'Intermediate' },
          { skill_name: 'Cable Pulling', min_proficiency: 'Beginner' },
        ],
        required_certs: ['OSHA 10'],
        skill_weights: { 'Fiber Splicing': 0.5, 'Cable Pulling': 0.4, 'Safety': 0.1 },
        quantity: 4,
        filled: 3,
        hourly_rate: 42,
        per_diem: 75,
      },
      {
        id: 'role-003',
        project_id: 'proj-001',
        role_name: 'OTDR Tester',
        skill_bundle: [
          { skill_name: 'OTDR Testing', min_proficiency: 'Intermediate' },
          { skill_name: 'Fiber Splicing', min_proficiency: 'Beginner' },
        ],
        required_certs: ['CFOT'],
        skill_weights: { 'OTDR Testing': 0.7, 'Fiber Splicing': 0.2, 'Safety': 0.1 },
        quantity: 2,
        filled: 1,
        hourly_rate: 48,
        per_diem: 75,
      },
    ],
    assignments: [
      {
        id: 'asgn-001',
        project_id: 'proj-001',
        role_id: 'role-001',
        technician_id: 'tech-001',
        technician_name: 'Marcus Johnson',
        role_name: 'Lead Splicer',
        start_date: '2026-01-15',
        end_date: '2026-06-30',
        hourly_rate: 55,
        per_diem: 85,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-002',
        project_id: 'proj-001',
        role_id: 'role-001',
        technician_id: 'tech-005',
        technician_name: 'David Chen',
        role_name: 'Lead Splicer',
        start_date: '2026-01-20',
        end_date: '2026-06-30',
        hourly_rate: 55,
        per_diem: 85,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-003',
        project_id: 'proj-001',
        role_id: 'role-002',
        technician_id: 'tech-008',
        technician_name: 'Sarah Williams',
        role_name: 'Fiber Technician',
        start_date: '2026-02-01',
        end_date: '2026-06-30',
        hourly_rate: 42,
        per_diem: 75,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-004',
        project_id: 'proj-001',
        role_id: 'role-002',
        technician_id: 'tech-012',
        technician_name: 'James Rodriguez',
        role_name: 'Fiber Technician',
        start_date: '2026-02-01',
        end_date: '2026-06-30',
        hourly_rate: 42,
        per_diem: 75,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-005',
        project_id: 'proj-001',
        role_id: 'role-002',
        technician_id: 'tech-015',
        technician_name: 'Emily Watson',
        role_name: 'Fiber Technician',
        start_date: '2026-02-15',
        end_date: '2026-06-30',
        hourly_rate: 42,
        per_diem: 75,
        assignment_type: 'active',
        status: 'Pending Confirmation',
        partner_confirmed: false,
      },
      {
        id: 'asgn-006',
        project_id: 'proj-001',
        role_id: 'role-003',
        technician_id: 'tech-020',
        technician_name: 'Robert Kim',
        role_name: 'OTDR Tester',
        start_date: '2026-01-20',
        end_date: '2026-06-30',
        hourly_rate: 48,
        per_diem: 75,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
    ],
    timesheets: [
      {
        id: 'ts-001',
        assignment_id: 'asgn-001',
        technician_id: 'tech-001',
        technician_name: 'Marcus Johnson',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 44,
        status: 'Approved',
        submitted_at: '2026-03-15T18:00:00Z',
      },
      {
        id: 'ts-002',
        assignment_id: 'asgn-003',
        technician_id: 'tech-008',
        technician_name: 'Sarah Williams',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 48,
        status: 'Flagged',
        flag_comment: 'Reported 48 hours but site access was restricted on Thursday - please verify',
        submitted_at: '2026-03-15T17:30:00Z',
      },
      {
        id: 'ts-003',
        assignment_id: 'asgn-002',
        technician_id: 'tech-005',
        technician_name: 'David Chen',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 40,
        status: 'Submitted',
        submitted_at: '2026-03-15T19:00:00Z',
      },
      {
        id: 'ts-004',
        assignment_id: 'asgn-004',
        technician_id: 'tech-012',
        technician_name: 'James Rodriguez',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 42,
        status: 'Approved',
        submitted_at: '2026-03-15T16:30:00Z',
      },
    ],
    escalations: [
      {
        id: 'esc-001',
        project_id: 'proj-001',
        assignment_id: 'asgn-005',
        technician_id: 'tech-015',
        technician_name: 'Emily Watson',
        type: 'confirmation',
        description: 'Partner confirmation pending for 3+ days - assignment start overdue. Lumen Technologies has not responded to the start date confirmation request.',
        status: 'Open',
        created_at: '2026-03-16T10:00:00Z',
        due_date: '2026-03-18T10:00:00Z',
        partner_id: 'partner-001',
        partner_name: 'Lumen Technologies',
        role_id: 'role-002',
        role_name: 'Fiber Technician',
        hours_waiting: 72,
        escalation_status: 'escalated',
        confirmation_type: 'start_date',
        requested_date: '2026-02-15',
      },
      {
        id: 'esc-002',
        project_id: 'proj-001',
        assignment_id: 'asgn-003',
        technician_id: 'tech-008',
        technician_name: 'Sarah Williams',
        type: 'timesheet_dispute',
        description: 'Flagged timesheet for week of Mar 9-15 requires ops review - reported 48 hours but site access was restricted on Thursday',
        status: 'Open',
        created_at: '2026-03-16T12:00:00Z',
        due_date: '2026-03-19T12:00:00Z',
        role_name: 'Fiber Technician',
        hours_waiting: 48,
        escalation_status: 'ops_reviewing',
      },
      {
        id: 'esc-003',
        project_id: 'proj-001',
        assignment_id: 'asgn-001',
        technician_id: 'tech-001',
        technician_name: 'Marcus Johnson',
        type: 'confirmation',
        description: 'End date confirmation was resolved - partner confirmed via ops override',
        status: 'Resolved',
        created_at: '2026-03-10T09:00:00Z',
        due_date: '2026-03-12T09:00:00Z',
        partner_id: 'partner-001',
        partner_name: 'Lumen Technologies',
        role_name: 'Lead Splicer',
        escalation_status: 'resolved_confirmed',
        resolution_note: 'Partner confirmed via phone call. Updated system manually.',
        resolved_at: '2026-03-11T14:30:00Z',
        resolved_by: 'ops-admin',
        confirmation_type: 'end_date',
        requested_date: '2026-06-30',
      },
    ],
  },
  {
    id: 'proj-002',
    name: 'Data Center Cabling - Dallas',
    status: 'Staffing',
    location_region: 'Texas',
    location_city: 'Dallas',
    start_date: '2026-04-01',
    end_date: '2026-09-15',
    partner_id: 'partner-002',
    partner_name: 'Equinix',
    description: 'Structured cabling installation for new 50MW data center facility. Includes fiber backbone, copper distribution, and cable management systems.',
    roles: [
      {
        id: 'role-004',
        project_id: 'proj-002',
        role_name: 'Senior Cable Tech',
        skill_bundle: [
          { skill_name: 'Structured Cabling', min_proficiency: 'Advanced' },
          { skill_name: 'Cable Management', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['BICSI RCDD', 'OSHA 30'],
        skill_weights: { 'Structured Cabling': 0.5, 'Cable Management': 0.3, 'Safety': 0.2 },
        quantity: 3,
        filled: 1,
        hourly_rate: 52,
        per_diem: 90,
      },
      {
        id: 'role-005',
        project_id: 'proj-002',
        role_name: 'Fiber Installer',
        skill_bundle: [
          { skill_name: 'Fiber Splicing', min_proficiency: 'Intermediate' },
          { skill_name: 'Cable Pulling', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['CFOT', 'OSHA 10'],
        skill_weights: { 'Fiber Splicing': 0.4, 'Cable Pulling': 0.4, 'Safety': 0.2 },
        quantity: 6,
        filled: 2,
        hourly_rate: 44,
        per_diem: 80,
      },
      {
        id: 'role-006',
        project_id: 'proj-002',
        role_name: 'Cable Puller',
        skill_bundle: [
          { skill_name: 'Cable Pulling', min_proficiency: 'Beginner' },
        ],
        required_certs: ['OSHA 10'],
        skill_weights: { 'Cable Pulling': 0.7, 'Safety': 0.3 },
        quantity: 8,
        filled: 0,
        hourly_rate: 32,
        per_diem: 65,
      },
    ],
    assignments: [
      {
        id: 'asgn-007',
        project_id: 'proj-002',
        role_id: 'role-004',
        technician_id: 'tech-003',
        technician_name: 'Michael Torres',
        role_name: 'Senior Cable Tech',
        start_date: '2026-04-01',
        end_date: '2026-09-15',
        hourly_rate: 52,
        per_diem: 90,
        assignment_type: 'pre-booked',
        status: 'Pending Confirmation',
        partner_confirmed: false,
      },
      {
        id: 'asgn-008',
        project_id: 'proj-002',
        role_id: 'role-005',
        technician_id: 'tech-010',
        technician_name: 'Lisa Park',
        role_name: 'Fiber Installer',
        start_date: '2026-04-01',
        end_date: '2026-09-15',
        hourly_rate: 44,
        per_diem: 80,
        assignment_type: 'pre-booked',
        status: 'Pending Confirmation',
        partner_confirmed: false,
      },
      {
        id: 'asgn-009',
        project_id: 'proj-002',
        role_id: 'role-005',
        technician_id: 'tech-018',
        technician_name: 'Kevin Brown',
        role_name: 'Fiber Installer',
        start_date: '2026-04-01',
        end_date: '2026-09-15',
        hourly_rate: 44,
        per_diem: 80,
        assignment_type: 'pre-booked',
        status: 'Pending Confirmation',
        partner_confirmed: false,
      },
    ],
    timesheets: [],
    escalations: [
      {
        id: 'esc-004',
        project_id: 'proj-002',
        assignment_id: 'asgn-007',
        technician_id: 'tech-003',
        technician_name: 'Michael Torres',
        type: 'confirmation',
        description: 'Equinix has not confirmed Senior Cable Tech assignment start date. Pre-booked assignment at risk.',
        status: 'Open',
        created_at: '2026-03-17T08:00:00Z',
        due_date: '2026-03-20T08:00:00Z',
        partner_id: 'partner-002',
        partner_name: 'Equinix',
        role_id: 'role-004',
        role_name: 'Senior Cable Tech',
        hours_waiting: 48,
        escalation_status: 'escalated',
        confirmation_type: 'start_date',
        requested_date: '2026-04-01',
      },
      {
        id: 'esc-005',
        project_id: 'proj-002',
        assignment_id: 'asgn-008',
        technician_id: 'tech-010',
        technician_name: 'Lisa Park',
        type: 'confirmation',
        description: 'Fiber Installer assignment pending partner confirmation for over 36 hours.',
        status: 'Open',
        created_at: '2026-03-17T14:00:00Z',
        due_date: '2026-03-20T14:00:00Z',
        partner_id: 'partner-002',
        partner_name: 'Equinix',
        role_id: 'role-005',
        role_name: 'Fiber Installer',
        hours_waiting: 36,
        escalation_status: 'escalated',
        confirmation_type: 'start_date',
        requested_date: '2026-04-01',
      },
    ],
  },
  {
    id: 'proj-003',
    name: 'FTTH Rollout - Charlotte',
    status: 'Active',
    location_region: 'North Carolina',
    location_city: 'Charlotte',
    start_date: '2025-11-01',
    end_date: '2026-05-31',
    partner_id: 'partner-003',
    partner_name: 'AT&T',
    description: 'Fiber-to-the-home deployment in suburban Charlotte neighborhoods. Installation of ONTs, drop cables, and customer premises equipment.',
    roles: [
      {
        id: 'role-007',
        project_id: 'proj-003',
        role_name: 'FTTH Installer',
        skill_bundle: [
          { skill_name: 'FTTH Installation', min_proficiency: 'Intermediate' },
          { skill_name: 'Fiber Splicing', min_proficiency: 'Beginner' },
        ],
        required_certs: ['CFOT', 'OSHA 10'],
        skill_weights: { 'FTTH Installation': 0.6, 'Fiber Splicing': 0.3, 'Safety': 0.1 },
        quantity: 5,
        filled: 5,
        hourly_rate: 40,
        per_diem: 70,
      },
      {
        id: 'role-008',
        project_id: 'proj-003',
        role_name: 'Field Supervisor',
        skill_bundle: [
          { skill_name: 'FTTH Installation', min_proficiency: 'Advanced' },
          { skill_name: 'OTDR Testing', min_proficiency: 'Intermediate' },
          { skill_name: 'Project Management', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['CFOT', 'OSHA 30'],
        skill_weights: { 'FTTH Installation': 0.3, 'OTDR Testing': 0.2, 'Project Management': 0.4, 'Safety': 0.1 },
        quantity: 1,
        filled: 1,
        hourly_rate: 58,
        per_diem: 95,
      },
    ],
    assignments: [
      {
        id: 'asgn-010',
        project_id: 'proj-003',
        role_id: 'role-008',
        technician_id: 'tech-002',
        technician_name: 'Angela Martinez',
        role_name: 'Field Supervisor',
        start_date: '2025-11-01',
        end_date: '2026-05-31',
        hourly_rate: 58,
        per_diem: 95,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-011',
        project_id: 'proj-003',
        role_id: 'role-007',
        technician_id: 'tech-006',
        technician_name: 'Carlos Rivera',
        role_name: 'FTTH Installer',
        start_date: '2025-11-01',
        end_date: '2026-05-31',
        hourly_rate: 40,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-012',
        project_id: 'proj-003',
        role_id: 'role-007',
        technician_id: 'tech-009',
        technician_name: 'Maria Santos',
        role_name: 'FTTH Installer',
        start_date: '2025-11-15',
        end_date: '2026-05-31',
        hourly_rate: 40,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-013',
        project_id: 'proj-003',
        role_id: 'role-007',
        technician_id: 'tech-014',
        technician_name: 'Tyler Jackson',
        role_name: 'FTTH Installer',
        start_date: '2025-12-01',
        end_date: '2026-05-31',
        hourly_rate: 40,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-014',
        project_id: 'proj-003',
        role_id: 'role-007',
        technician_id: 'tech-022',
        technician_name: 'Nicole Adams',
        role_name: 'FTTH Installer',
        start_date: '2025-12-01',
        end_date: '2026-05-31',
        hourly_rate: 40,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-015',
        project_id: 'proj-003',
        role_id: 'role-007',
        technician_id: 'tech-025',
        technician_name: 'Brandon Lee',
        role_name: 'FTTH Installer',
        start_date: '2026-01-05',
        end_date: '2026-05-31',
        hourly_rate: 40,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
    ],
    timesheets: [
      {
        id: 'ts-005',
        assignment_id: 'asgn-010',
        technician_id: 'tech-002',
        technician_name: 'Angela Martinez',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 45,
        status: 'Approved',
        submitted_at: '2026-03-15T17:00:00Z',
      },
      {
        id: 'ts-006',
        assignment_id: 'asgn-011',
        technician_id: 'tech-006',
        technician_name: 'Carlos Rivera',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 40,
        status: 'Approved',
        submitted_at: '2026-03-15T16:00:00Z',
      },
    ],
    escalations: [],
  },
  {
    id: 'proj-004',
    name: 'OSP Backbone - Denver',
    status: 'Wrapping Up',
    location_region: 'Colorado',
    location_city: 'Denver',
    start_date: '2025-08-01',
    end_date: '2026-03-31',
    partner_id: 'partner-001',
    partner_name: 'Lumen Technologies',
    description: 'Outside plant fiber backbone construction along the I-25 corridor. Long-haul fiber deployment with splice closures and hand holes.',
    roles: [
      {
        id: 'role-009',
        project_id: 'proj-004',
        role_name: 'OSP Splicer',
        skill_bundle: [
          { skill_name: 'Fiber Splicing', min_proficiency: 'Advanced' },
          { skill_name: 'Aerial Installation', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['CFOT', 'OSHA 30', 'CDL Class B'],
        skill_weights: { 'Fiber Splicing': 0.5, 'Aerial Installation': 0.3, 'Safety': 0.2 },
        quantity: 3,
        filled: 3,
        hourly_rate: 58,
        per_diem: 100,
      },
    ],
    assignments: [
      {
        id: 'asgn-016',
        project_id: 'proj-004',
        role_id: 'role-009',
        technician_id: 'tech-004',
        technician_name: 'William Chen',
        role_name: 'OSP Splicer',
        start_date: '2025-08-01',
        end_date: '2026-03-31',
        hourly_rate: 58,
        per_diem: 100,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-017',
        project_id: 'proj-004',
        role_id: 'role-009',
        technician_id: 'tech-007',
        technician_name: 'Patricia Nguyen',
        role_name: 'OSP Splicer',
        start_date: '2025-08-15',
        end_date: '2026-03-31',
        hourly_rate: 58,
        per_diem: 100,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-018',
        project_id: 'proj-004',
        role_id: 'role-009',
        technician_id: 'tech-011',
        technician_name: 'Daniel Washington',
        role_name: 'OSP Splicer',
        start_date: '2025-09-01',
        end_date: '2026-03-31',
        hourly_rate: 58,
        per_diem: 100,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
    ],
    timesheets: [
      {
        id: 'ts-007',
        assignment_id: 'asgn-016',
        technician_id: 'tech-004',
        technician_name: 'William Chen',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 38,
        status: 'Submitted',
        submitted_at: '2026-03-15T20:00:00Z',
      },
    ],
    escalations: [],
  },
  {
    id: 'proj-005',
    name: '5G Small Cell Deployment - Miami',
    status: 'Staffing',
    location_region: 'Florida',
    location_city: 'Miami',
    start_date: '2026-05-01',
    end_date: '2026-12-31',
    partner_id: 'partner-004',
    partner_name: 'Crown Castle',
    description: 'Small cell and DAS installation across downtown Miami. Includes pole-mounted fiber attachments and rooftop equipment installation.',
    roles: [
      {
        id: 'role-010',
        project_id: 'proj-005',
        role_name: 'Small Cell Installer',
        skill_bundle: [
          { skill_name: 'Small Cell Installation', min_proficiency: 'Intermediate' },
          { skill_name: 'Aerial Installation', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['OSHA 30', 'RF Safety'],
        skill_weights: { 'Small Cell Installation': 0.5, 'Aerial Installation': 0.3, 'Safety': 0.2 },
        quantity: 4,
        filled: 0,
        hourly_rate: 48,
        per_diem: 85,
      },
      {
        id: 'role-011',
        project_id: 'proj-005',
        role_name: 'RF Engineer',
        skill_bundle: [
          { skill_name: 'RF Testing', min_proficiency: 'Advanced' },
          { skill_name: 'Small Cell Installation', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['RF Safety', 'OSHA 10'],
        skill_weights: { 'RF Testing': 0.6, 'Small Cell Installation': 0.3, 'Safety': 0.1 },
        quantity: 2,
        filled: 0,
        hourly_rate: 62,
        per_diem: 95,
      },
    ],
    assignments: [],
    timesheets: [],
    escalations: [],
  },
  {
    id: 'proj-006',
    name: 'Campus Fiber Network - Austin',
    status: 'Draft',
    location_region: 'Texas',
    location_city: 'Austin',
    start_date: '2026-07-01',
    end_date: '2026-11-30',
    partner_id: 'partner-002',
    partner_name: 'Equinix',
    description: 'Enterprise campus fiber network installation for new corporate campus. Includes conduit, fiber plant, and termination in 5 buildings.',
    roles: [
      {
        id: 'role-012',
        project_id: 'proj-006',
        role_name: 'Fiber Technician',
        skill_bundle: [
          { skill_name: 'Fiber Splicing', min_proficiency: 'Intermediate' },
          { skill_name: 'Structured Cabling', min_proficiency: 'Beginner' },
        ],
        required_certs: ['CFOT', 'OSHA 10'],
        skill_weights: { 'Fiber Splicing': 0.5, 'Structured Cabling': 0.4, 'Safety': 0.1 },
        quantity: 3,
        filled: 0,
        hourly_rate: 44,
        per_diem: 75,
      },
    ],
    assignments: [],
    timesheets: [],
    escalations: [],
  },
  {
    id: 'proj-007',
    name: 'Enterprise WAN Upgrade - Atlanta',
    status: 'Active',
    location_region: 'Georgia',
    location_city: 'Atlanta',
    start_date: '2026-02-01',
    end_date: '2026-08-31',
    partner_id: 'partner-005',
    partner_name: 'Zayo Group',
    description: 'Multi-site WAN upgrade for enterprise client. Fiber and copper infrastructure upgrades across 12 office locations in the Atlanta metro area.',
    roles: [
      {
        id: 'role-013',
        project_id: 'proj-007',
        role_name: 'Network Technician',
        skill_bundle: [
          { skill_name: 'Structured Cabling', min_proficiency: 'Intermediate' },
          { skill_name: 'Fiber Splicing', min_proficiency: 'Beginner' },
        ],
        required_certs: ['BICSI Installer', 'OSHA 10'],
        skill_weights: { 'Structured Cabling': 0.5, 'Fiber Splicing': 0.3, 'Safety': 0.2 },
        quantity: 4,
        filled: 3,
        hourly_rate: 42,
        per_diem: 70,
      },
      {
        id: 'role-014',
        project_id: 'proj-007',
        role_name: 'Project Lead',
        skill_bundle: [
          { skill_name: 'Project Management', min_proficiency: 'Advanced' },
          { skill_name: 'Structured Cabling', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['BICSI RCDD', 'OSHA 30'],
        skill_weights: { 'Project Management': 0.5, 'Structured Cabling': 0.3, 'Safety': 0.2 },
        quantity: 1,
        filled: 1,
        hourly_rate: 60,
        per_diem: 95,
      },
    ],
    assignments: [
      {
        id: 'asgn-019',
        project_id: 'proj-007',
        role_id: 'role-014',
        technician_id: 'tech-016',
        technician_name: 'Christopher Davis',
        role_name: 'Project Lead',
        start_date: '2026-02-01',
        end_date: '2026-08-31',
        hourly_rate: 60,
        per_diem: 95,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-020',
        project_id: 'proj-007',
        role_id: 'role-013',
        technician_id: 'tech-019',
        technician_name: 'Amanda Foster',
        role_name: 'Network Technician',
        start_date: '2026-02-01',
        end_date: '2026-08-31',
        hourly_rate: 42,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-021',
        project_id: 'proj-007',
        role_id: 'role-013',
        technician_id: 'tech-023',
        technician_name: 'Ryan Mitchell',
        role_name: 'Network Technician',
        start_date: '2026-02-15',
        end_date: '2026-08-31',
        hourly_rate: 42,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
      {
        id: 'asgn-022',
        project_id: 'proj-007',
        role_id: 'role-013',
        technician_id: 'tech-028',
        technician_name: 'Jessica Thompson',
        role_name: 'Network Technician',
        start_date: '2026-03-01',
        end_date: '2026-08-31',
        hourly_rate: 42,
        per_diem: 70,
        assignment_type: 'active',
        status: 'Active',
        partner_confirmed: true,
      },
    ],
    timesheets: [
      {
        id: 'ts-008',
        assignment_id: 'asgn-019',
        technician_id: 'tech-016',
        technician_name: 'Christopher Davis',
        week_start: '2026-03-09',
        week_end: '2026-03-15',
        hours: 40,
        status: 'Approved',
        submitted_at: '2026-03-15T17:00:00Z',
      },
    ],
    escalations: [],
  },
  {
    id: 'proj-008',
    name: 'Municipal Fiber Build - Portland',
    status: 'Closed',
    location_region: 'Oregon',
    location_city: 'Portland',
    start_date: '2025-03-01',
    end_date: '2025-12-15',
    partner_id: 'partner-003',
    partner_name: 'AT&T',
    description: 'City-wide municipal broadband fiber network. Completed ahead of schedule with all fiber strands tested and documented.',
    roles: [
      {
        id: 'role-015',
        project_id: 'proj-008',
        role_name: 'Fiber Splicer',
        skill_bundle: [
          { skill_name: 'Fiber Splicing', min_proficiency: 'Intermediate' },
        ],
        required_certs: ['CFOT'],
        skill_weights: { 'Fiber Splicing': 0.8, 'Safety': 0.2 },
        quantity: 6,
        filled: 6,
        hourly_rate: 46,
        per_diem: 80,
      },
    ],
    assignments: [],
    timesheets: [],
    escalations: [],
  },
]
