import type { Technician, Assignment, Timesheet, NextStepCard, SkillBreakdown } from '@/types'

// ============================================================
// Technician Portal Seed Data — perspective of a single tech
// ============================================================

export const seedTechnician: Technician = {
  id: 'tech-012',
  name: 'Marcus Rivera',
  email: 'marcus.rivera@email.com',
  phone: '(214) 555-0187',
  home_base_city: 'Dallas, TX',
  approved_regions: ['TX', 'AZ', 'NM', 'OK', 'CO'],
  career_stage: 'Deployed',
  deployability_status: 'Currently Assigned',
  deployability_locked: false,
  available_from: '2026-04-15',
  skills: [
    { skill_name: 'Fiber Splicing', proficiency_level: 'Advanced', training_hours_accumulated: 480 },
    { skill_name: 'OTDR Testing', proficiency_level: 'Advanced', training_hours_accumulated: 320 },
    { skill_name: 'Cable Pulling', proficiency_level: 'Intermediate', training_hours_accumulated: 210 },
    { skill_name: 'Network Termination', proficiency_level: 'Intermediate', training_hours_accumulated: 150 },
    { skill_name: 'Aerial Installation', proficiency_level: 'Beginner', training_hours_accumulated: 45 },
  ],
  certifications: [
    { cert_name: 'CFOT', issue_date: '2025-06-15', expiry_date: '2027-06-15', status: 'Active' },
    { cert_name: 'OSHA 30', issue_date: '2025-01-10', expiry_date: '2026-07-10', status: 'Active' },
    { cert_name: 'OSHA 10', issue_date: '2024-08-20', expiry_date: '2026-08-20', status: 'Active' },
    { cert_name: 'BICSI Installer 1', issue_date: '2025-03-01', expiry_date: '2026-09-01', status: 'Active' },
    { cert_name: 'First Aid/CPR', issue_date: '2025-11-15', expiry_date: '2026-05-15', status: 'Expiring Soon' },
  ],
  documents: [
    { doc_type: 'Driver License', verification_status: 'Verified' },
    { doc_type: 'Background Check', verification_status: 'Verified' },
    { doc_type: 'Drug Test', verification_status: 'Verified' },
    { doc_type: 'W-4 Form', verification_status: 'Verified' },
    { doc_type: 'Vehicle Insurance', verification_status: 'Expired' },
  ],
  site_badges: ['AT&T Certified', 'Verizon Approved', 'Lumen Partner'],
  milestone_badges: ['1000+ Hours', '5 Projects Completed', 'Zero Safety Incidents'],
  avatar_url: undefined,
} as Technician

export const seedAssignments: Assignment[] = [
  {
    id: 'asgn-101',
    project_id: 'proj-002',
    project_name: 'Austin Metro Fiber Expansion',
    role_id: 'role-201',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    role_name: 'Lead Splicer',
    start_date: '2026-02-01',
    end_date: '2026-04-15',
    hourly_rate: 42.0,
    per_diem: 85.0,
    assignment_type: 'active',
    status: 'Active',
  },
  {
    id: 'asgn-102',
    project_id: 'proj-003',
    project_name: 'Phoenix Metro Fiber Build',
    role_id: 'role-301',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    role_name: 'Lead Splicer',
    start_date: '2026-04-20',
    end_date: '2026-07-30',
    hourly_rate: 45.0,
    per_diem: 95.0,
    assignment_type: 'pre-booked',
    status: 'Pending Confirmation',
  },
]

export const seedTimesheets: Timesheet[] = [
  {
    id: 'ts-202',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-03-16',
    week_end: '2026-03-22',
    hours: 40,
    status: 'Submitted',
    submitted_at: '2026-03-19T08:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
  {
    id: 'ts-201',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-03-09',
    week_end: '2026-03-15',
    hours: 44,
    status: 'Approved',
    submitted_at: '2026-03-15T17:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
  {
    id: 'ts-203',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-03-02',
    week_end: '2026-03-08',
    hours: 42,
    status: 'Approved',
    submitted_at: '2026-03-08T17:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
  {
    id: 'ts-204',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-02-23',
    week_end: '2026-03-01',
    hours: 38,
    status: 'Flagged',
    flag_comment: 'Hours seem low for the week — please verify if any PTO was taken',
    submitted_at: '2026-03-01T17:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
  {
    id: 'ts-205',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-02-16',
    week_end: '2026-02-22',
    hours: 45,
    status: 'Approved',
    submitted_at: '2026-02-22T17:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
  {
    id: 'ts-206',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-02-09',
    week_end: '2026-02-15',
    hours: 40,
    status: 'Approved',
    submitted_at: '2026-02-15T17:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
  {
    id: 'ts-207',
    assignment_id: 'asgn-101',
    technician_id: 'tech-012',
    technician_name: 'Marcus Rivera',
    week_start: '2026-02-02',
    week_end: '2026-02-08',
    hours: 42,
    status: 'Approved',
    submitted_at: '2026-02-08T17:00:00Z',
    project_name: 'Austin Metro Fiber Expansion',
  },
]

export const seedNextStepCard: NextStepCard = {
  id: 'ns-001',
  action: 'Renew your First Aid/CPR certification',
  reasoning: 'Your First Aid/CPR certification expires on May 15, 2026 — less than 60 days away. Several upcoming projects require active First Aid/CPR. Renewing now ensures uninterrupted deployability.',
  priority: 'high',
  link: '/tech/certifications',
  type: 'certification',
}

export const seedSkillBreakdowns: SkillBreakdown[] = [
  {
    id: 'sb-001',
    assignment_id: 'asgn-100',
    technician_id: 'tech-012',
    submitted_by: 'tech-012',
    skill_weights: {
      'Fiber Splicing': 0.45,
      'OTDR Testing': 0.30,
      'Cable Pulling': 0.15,
      'Network Termination': 0.10,
    },
    status: 'Approved',
    submitted_at: '2026-01-28T00:00:00Z',
  },
]
